// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    jdccs "github.com/jdcloud-api/jdcloud-sdk-go/services/jdccs/models"
    common "github.com/jdcloud-api/jdcloud-sdk-go/services/common/models"
)

type DescribeResourceBandwidthTrafficsRequest struct {

    core.JDCloudRequest

    /* 页码, 默认为1 (Optional) */
    PageNumber *int `json:"pageNumber"`

    /* 分页大小，默认为20 (Optional) */
    PageSize *int `json:"pageSize"`

    /* 带宽（出口）名称 (Optional) */
    BandwidthName *string `json:"bandwidthName"`

    /* idcDatacenterName - idc机房名称，精确匹配，支持多个
cdnDatacenterName - cdn机房名称，精确匹配，支持多个
regionEn - 托管区，精确匹配，支持多个
 (Optional) */
    Filters []common.Filter `json:"filters"`
}

/*
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDescribeResourceBandwidthTrafficsRequest(
) *DescribeResourceBandwidthTrafficsRequest {

	return &DescribeResourceBandwidthTrafficsRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/bandwidthTraffics",
			Method:  "GET",
			Header:  nil,
			Version: "v1",
		},
	}
}

/*
 * param pageNumber: 页码, 默认为1 (Optional)
 * param pageSize: 分页大小，默认为20 (Optional)
 * param bandwidthName: 带宽（出口）名称 (Optional)
 * param filters: idcDatacenterName - idc机房名称，精确匹配，支持多个
cdnDatacenterName - cdn机房名称，精确匹配，支持多个
regionEn - 托管区，精确匹配，支持多个
 (Optional)
 */
func NewDescribeResourceBandwidthTrafficsRequestWithAllParams(
    pageNumber *int,
    pageSize *int,
    bandwidthName *string,
    filters []common.Filter,
) *DescribeResourceBandwidthTrafficsRequest {

    return &DescribeResourceBandwidthTrafficsRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/bandwidthTraffics",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
        PageNumber: pageNumber,
        PageSize: pageSize,
        BandwidthName: bandwidthName,
        Filters: filters,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDescribeResourceBandwidthTrafficsRequestWithoutParam() *DescribeResourceBandwidthTrafficsRequest {

    return &DescribeResourceBandwidthTrafficsRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/bandwidthTraffics",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param pageNumber: 页码, 默认为1(Optional) */
func (r *DescribeResourceBandwidthTrafficsRequest) SetPageNumber(pageNumber int) {
    r.PageNumber = &pageNumber
}
/* param pageSize: 分页大小，默认为20(Optional) */
func (r *DescribeResourceBandwidthTrafficsRequest) SetPageSize(pageSize int) {
    r.PageSize = &pageSize
}
/* param bandwidthName: 带宽（出口）名称(Optional) */
func (r *DescribeResourceBandwidthTrafficsRequest) SetBandwidthName(bandwidthName string) {
    r.BandwidthName = &bandwidthName
}
/* param filters: idcDatacenterName - idc机房名称，精确匹配，支持多个
cdnDatacenterName - cdn机房名称，精确匹配，支持多个
regionEn - 托管区，精确匹配，支持多个
(Optional) */
func (r *DescribeResourceBandwidthTrafficsRequest) SetFilters(filters []common.Filter) {
    r.Filters = filters
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DescribeResourceBandwidthTrafficsRequest) GetRegionId() string {
    return ""
}

type DescribeResourceBandwidthTrafficsResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DescribeResourceBandwidthTrafficsResult `json:"result"`
}

type DescribeResourceBandwidthTrafficsResult struct {
    BandwidthTraffics []jdccs.DescribeResourceBandwidthTraffic `json:"bandwidthTraffics"`
    PageNumber int `json:"pageNumber"`
    PageSize int `json:"pageSize"`
    TotalCount int `json:"totalCount"`
}