// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    jdstarrocks "github.com/jdcloud-api/jdcloud-sdk-go/services/jdstarrocks/models"
)

type ProjectAlarmRulesRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /* 实例code (Optional) */
    ProjectCode *string `json:"projectCode"`

    /* 规则code (Optional) */
    RulesCode *string `json:"rulesCode"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewProjectAlarmRulesRequest(
    regionId string,
    appName string,
) *ProjectAlarmRulesRequest {

	return &ProjectAlarmRulesRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/projectAlarmRules",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        AppName: appName,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param projectCode: 实例code (Optional)
 * param rulesCode: 规则code (Optional)
 */
func NewProjectAlarmRulesRequestWithAllParams(
    regionId string,
    appName string,
    projectCode *string,
    rulesCode *string,
) *ProjectAlarmRulesRequest {

    return &ProjectAlarmRulesRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/projectAlarmRules",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        AppName: appName,
        ProjectCode: projectCode,
        RulesCode: rulesCode,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewProjectAlarmRulesRequestWithoutParam() *ProjectAlarmRulesRequest {

    return &ProjectAlarmRulesRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/projectAlarmRules",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *ProjectAlarmRulesRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *ProjectAlarmRulesRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param projectCode: 实例code(Optional) */
func (r *ProjectAlarmRulesRequest) SetProjectCode(projectCode string) {
    r.ProjectCode = &projectCode
}
/* param rulesCode: 规则code(Optional) */
func (r *ProjectAlarmRulesRequest) SetRulesCode(rulesCode string) {
    r.RulesCode = &rulesCode
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r ProjectAlarmRulesRequest) GetRegionId() string {
    return r.RegionId
}

type ProjectAlarmRulesResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result ProjectAlarmRulesResult `json:"result"`
}

type ProjectAlarmRulesResult struct {
    Code string `json:"code"`
    Message string `json:"message"`
    RequestId string `json:"requestId"`
    Result jdstarrocks.ProjectAlarmRulesRes `json:"result"`
}