// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    jdstarrocks "github.com/jdcloud-api/jdcloud-sdk-go/services/jdstarrocks/models"
)

type RicGetProjectUserNamePwdRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /*  (Optional) */
    ProjectCode *string `json:"projectCode"`

    /*  (Optional) */
    UserName *string `json:"userName"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewRicGetProjectUserNamePwdRequest(
    regionId string,
    appName string,
) *RicGetProjectUserNamePwdRequest {

	return &RicGetProjectUserNamePwdRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/ricricGetProjectUserNamePwd",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        AppName: appName,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param projectCode:  (Optional)
 * param userName:  (Optional)
 */
func NewRicGetProjectUserNamePwdRequestWithAllParams(
    regionId string,
    appName string,
    projectCode *string,
    userName *string,
) *RicGetProjectUserNamePwdRequest {

    return &RicGetProjectUserNamePwdRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/ricricGetProjectUserNamePwd",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        AppName: appName,
        ProjectCode: projectCode,
        UserName: userName,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewRicGetProjectUserNamePwdRequestWithoutParam() *RicGetProjectUserNamePwdRequest {

    return &RicGetProjectUserNamePwdRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/ricricGetProjectUserNamePwd",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *RicGetProjectUserNamePwdRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *RicGetProjectUserNamePwdRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param projectCode: (Optional) */
func (r *RicGetProjectUserNamePwdRequest) SetProjectCode(projectCode string) {
    r.ProjectCode = &projectCode
}
/* param userName: (Optional) */
func (r *RicGetProjectUserNamePwdRequest) SetUserName(userName string) {
    r.UserName = &userName
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r RicGetProjectUserNamePwdRequest) GetRegionId() string {
    return r.RegionId
}

type RicGetProjectUserNamePwdResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result RicGetProjectUserNamePwdResult `json:"result"`
}

type RicGetProjectUserNamePwdResult struct {
    Code string `json:"code"`
    Message string `json:"message"`
    RequestId string `json:"requestId"`
    Result []jdstarrocks.RicGetProjectUserNamePwdRes `json:"result"`
}