// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type BindJdsfGroup struct {

    /* 微服务网关名称 (Optional) */
    JdsfName string `json:"jdsfName"`

    /* 微服务注册中心ID (Optional) */
    JdsfRegistryName string `json:"jdsfRegistryName"`

    /* 环境信息  */
    Environment string `json:"environment"`

    /* 微服务网关ID  */
    JdsfId string `json:"jdsfId"`

    /* VPC类型时，传vpc对应的IP:port (Optional) */
    JdsfParam string `json:"jdsfParam"`

    /* 微服务网关region ID (Optional) */
    JdsfRegion string `json:"jdsfRegion"`

    /* 分组类型：api_group（api分组）、jdsf_group（微服务分组）默认api_group (Optional) */
    GroupType string `json:"groupType"`
}
