// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type AnticheatResult struct {

    /* 本次请求数据标识，可以根据该标识查询数据最新结果 (Optional) */
    TaskId string `json:"taskId"`

    /* 检测结果，0：通过，10：嫌疑，20：不通过 (Optional) */
    Action int `json:"action"`

    /* 命中信息，例如：[{"hitType":5,"hitMsg":"无SDK数据"}]，其中hitType类型为int，含义是命中类型，详见 hitType返回码及含义表。hitMsg类型为String，含义是命中详情，可定制返回值。 (Optional) */
    HitInfos []HitInfo `json:"hitInfos"`
}
