// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    starshield "github.com/jdcloud-api/jdcloud-sdk-go/services/starshield/models"
)

type DashboardRequest struct {

    core.JDCloudRequest

    /*   */
    Zone_identifier string `json:"zone_identifier"`

    /*   */
    ZoneName string `json:"zoneName"`

    /*   */
    Since string `json:"since"`

    /*   */
    Until string `json:"until"`

    /*  (Optional) */
    Category *string `json:"category"`

    /*  (Optional) */
    Filters []starshield.AnalyticsReportingFilter `json:"filters"`
}

/*
 * param zone_identifier:  (Required)
 * param zoneName:  (Required)
 * param since:  (Required)
 * param until:  (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDashboardRequest(
    zone_identifier string,
    zoneName string,
    since string,
    until string,
) *DashboardRequest {

	return &DashboardRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/zones/{zone_identifier}/analytics$$dashboard",
			Method:  "GET",
			Header:  nil,
			Version: "v1",
		},
        Zone_identifier: zone_identifier,
        ZoneName: zoneName,
        Since: since,
        Until: until,
	}
}

/*
 * param zone_identifier:  (Required)
 * param zoneName:  (Required)
 * param since:  (Required)
 * param until:  (Required)
 * param category:  (Optional)
 * param filters:  (Optional)
 */
func NewDashboardRequestWithAllParams(
    zone_identifier string,
    zoneName string,
    since string,
    until string,
    category *string,
    filters []starshield.AnalyticsReportingFilter,
) *DashboardRequest {

    return &DashboardRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/zones/{zone_identifier}/analytics$$dashboard",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
        Zone_identifier: zone_identifier,
        ZoneName: zoneName,
        Since: since,
        Until: until,
        Category: category,
        Filters: filters,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDashboardRequestWithoutParam() *DashboardRequest {

    return &DashboardRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/zones/{zone_identifier}/analytics$$dashboard",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param zone_identifier: (Required) */
func (r *DashboardRequest) SetZone_identifier(zone_identifier string) {
    r.Zone_identifier = zone_identifier
}
/* param zoneName: (Required) */
func (r *DashboardRequest) SetZoneName(zoneName string) {
    r.ZoneName = zoneName
}
/* param since: (Required) */
func (r *DashboardRequest) SetSince(since string) {
    r.Since = since
}
/* param until: (Required) */
func (r *DashboardRequest) SetUntil(until string) {
    r.Until = until
}
/* param category: (Optional) */
func (r *DashboardRequest) SetCategory(category string) {
    r.Category = &category
}
/* param filters: (Optional) */
func (r *DashboardRequest) SetFilters(filters []starshield.AnalyticsReportingFilter) {
    r.Filters = filters
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DashboardRequest) GetRegionId() string {
    return ""
}

type DashboardResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DashboardResult `json:"result"`
}

type DashboardResult struct {
    Totals starshield.Totals `json:"totals"`
    Timeseries []starshield.Totals `json:"timeseries"`
}