// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type TranscodeOutputParam struct {

    /* 输出对象存储 accessKey，可选参数，默认与输入 accessKey 保持一致 (Optional) */
    AccessKey string `json:"accessKey"`

    /* 输出对象存储 secretKey，可选参数，默认与输入 secretKey 保持一致 (Optional) */
    SecretKey string `json:"secretKey"`

    /* 输出对象存储 endpoint。可选参数，内网域名，默认与输入 endpoint 保持一致，如 s3-internal.cn-north-1.jcloudcs.com (Optional) */
    Endpoint string `json:"endpoint"`

    /* 输出对象存储 bucket，可选参数，默认与输入 bucket 保持一致 (Optional) */
    Bucket string `json:"bucket"`

    /* 输出集合，必须参数，非空集 (Optional) */
    Output TranscodeOutputObject `json:"output"`
}
