// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type UpdateWatermarkTemplateRequestInfo struct {

    /* 水印模板名称。长度不超过128个字符。  */
    Name string `json:"name"`

    /* 水印类型。取值范围：
  image - 图片明水印
  text - 文字明水印
  invisible - 文字暗水印
  */
    Type string `json:"type"`

    /* 水印图片链接（type=image时必填）（图片水印设置有效） (Optional) */
    ImageUrl string `json:"imageUrl"`

    /* 文字水印内容（type=text 或 invisible时必填，最长100个字符）（文字水印设置有效） (Optional) */
    Text string `json:"text"`

    /* 字体文件名称（type=text时可选，默认：LangZheng）
支持的字体文件:
  朗正.ttf
  尚酷.ttf
  机甲.ttf
  中秀体.ttf
  乐喵体.ttf
  糯米团.ttf
  雅酷黑.ttf
  汉真广标.ttf
  SourceHanSansCN-Normal.ttf
  simfang.ttf
对应的输入参数值：
  朗正 - LangZheng
  尚酷 - ShangKu
  机甲 - JiJia
  中秀体 - ZhongXiuTi
  乐喵体 - LeMiaoTi
  糯米团 - NuoMiTuan
  雅酷黑 - YaKuHei
  汉真广标 - HanZhenGuangBiao
  SourceHanSansCN-Normal - SourceHanSansCN-Normal
  simfang - FangSong
  （文字水印设置有效）
 (Optional) */
    FontFile string `json:"fontFile"`

    /* 字号（type=text时可选，默认24，单位像素）（文字水印设置有效） (Optional) */
    FontSize int `json:"fontSize"`

    /* 字体颜色（type=text时可选，默认#FFFFFF，格式#RRGGBB）（文字水印设置有效） (Optional) */
    FontColor string `json:"fontColor"`

    /* 字体透明度，取值范围：[0, 100]（type=text时可选）（文字水印设置有效） (Optional) */
    FontOpacity int `json:"fontOpacity"`

    /* 水印位置。取值范围：
  TL - 左上
  TR - 右上
  BL - 左下
  BR - 右下
  MC - 中间
（通用字段）
 (Optional) */
    Position string `json:"position"`

    /* 水印距离左侧偏移，取值范围：[1, 1920]（通用字段） (Optional) */
    OffsetX int `json:"offsetX"`

    /* 水印距离顶部偏移，取值范围：[1, 1920]（通用字段） (Optional) */
    OffsetY int `json:"offsetY"`

    /* 水印宽度（图片水印设置有效） (Optional) */
    Width int `json:"width"`

    /* 水印高度（图片水印设置有效） (Optional) */
    Height int `json:"height"`

    /* 水印宽度参考系数
当sizeUnit为percent时，用于指定计算实际水印宽度时的参考系数，实际宽度=width*widthRef
默认值：video
可选值：
logo（实际宽度=width*水印宽度像素数）
video（同video_width）
video_width（实际宽度=width*输出视频宽度）
video_height（实际宽度=width*输出视频高度）
video_longside（实际宽度=width*输出视频长边）
video_shortside（实际宽度=width*输出视频短边）
（图片水印设置有效）
 (Optional) */
    WidthRef string `json:"widthRef"`

    /* 水印高度参考系数
当sizeUnit为percent时，用于指定计算实际水印高度时的参考系数，实际高度=height*heightRef
默认值：video
可选值：
logo（实际高度=height*水印高度像素数）
video（同video_height）
video_width（实际高度=height*输出视频宽度）
video_height（实际高度=height*输出视频高度）
video_longside（实际高度=height*输出视频长边）
video_shortside（实际高度=height*输出视频短边）
（图片水印设置有效）
 (Optional) */
    HeightRef string `json:"heightRef"`

    /* 位置单位。取值范围：
  percent - 按百分比
  pixel - 按像素
缺省值为 pixel
（图片水印设置有效）
 (Optional) */
    SizeUnit string `json:"sizeUnit"`

    /* 水印边界距corner距离单位。取值范围：
  percent - 按百分比
  pixel - 按像素
缺省值为 pixel
（通用字段）
 (Optional) */
    OffsetUnit string `json:"offsetUnit"`

    /* 旋转角度，取值范围：[0, 360]，缺省值为0（文字水印设置有效） (Optional) */
    Rotation int `json:"rotation"`

    /* 阴影强度，取值范围：[0, 100]，缺省值为0（文字水印设置有效） (Optional) */
    Shadow int `json:"shadow"`

    /* 阴影颜色，格式#RRGGBB，缺省值为#000000（文字水印设置有效） (Optional) */
    ShadowColor string `json:"shadowColor"`

    /* 是否平铺水印，缺省值为false（文字水印设置有效） (Optional) */
    Tile bool `json:"tile"`

    /* 平铺间距百分比，取值范围：[0, 100]，缺省值为10（文字水印设置有效） (Optional) */
    TileSpacing int `json:"tileSpacing"`
}
