// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type CreateConfigTemplateRequest struct {

    core.JDCloudRequest

    /* 模板名称  */
    Name string `json:"name"`

    /* 模板描述 (Optional) */
    Description *string `json:"description"`

    /* 配置项键值对 (Optional) */
    Val *interface{} `json:"val"`

    /* Redis类型(master-slave/native-cluster)  */
    RedisType string `json:"redisType"`

    /* Redis版本(6.2/7.2/8.0等)  */
    RedisVersion string `json:"redisVersion"`
}

/*
 * param name: 模板名称 (Required)
 * param redisType: Redis类型(master-slave/native-cluster) (Required)
 * param redisVersion: Redis版本(6.2/7.2/8.0等) (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewCreateConfigTemplateRequest(
    name string,
    redisType string,
    redisVersion string,
) *CreateConfigTemplateRequest {

	return &CreateConfigTemplateRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/configTemplate",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        Name: name,
        RedisType: redisType,
        RedisVersion: redisVersion,
	}
}

/*
 * param name: 模板名称 (Required)
 * param description: 模板描述 (Optional)
 * param val: 配置项键值对 (Optional)
 * param redisType: Redis类型(master-slave/native-cluster) (Required)
 * param redisVersion: Redis版本(6.2/7.2/8.0等) (Required)
 */
func NewCreateConfigTemplateRequestWithAllParams(
    name string,
    description *string,
    val *interface{},
    redisType string,
    redisVersion string,
) *CreateConfigTemplateRequest {

    return &CreateConfigTemplateRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/configTemplate",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        Name: name,
        Description: description,
        Val: val,
        RedisType: redisType,
        RedisVersion: redisVersion,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewCreateConfigTemplateRequestWithoutParam() *CreateConfigTemplateRequest {

    return &CreateConfigTemplateRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/configTemplate",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param name: 模板名称(Required) */
func (r *CreateConfigTemplateRequest) SetName(name string) {
    r.Name = name
}
/* param description: 模板描述(Optional) */
func (r *CreateConfigTemplateRequest) SetDescription(description string) {
    r.Description = &description
}
/* param val: 配置项键值对(Optional) */
func (r *CreateConfigTemplateRequest) SetVal(val interface{}) {
    r.Val = &val
}
/* param redisType: Redis类型(master-slave/native-cluster)(Required) */
func (r *CreateConfigTemplateRequest) SetRedisType(redisType string) {
    r.RedisType = redisType
}
/* param redisVersion: Redis版本(6.2/7.2/8.0等)(Required) */
func (r *CreateConfigTemplateRequest) SetRedisVersion(redisVersion string) {
    r.RedisVersion = redisVersion
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r CreateConfigTemplateRequest) GetRegionId() string {
    return ""
}

type CreateConfigTemplateResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result CreateConfigTemplateResult `json:"result"`
}

type CreateConfigTemplateResult struct {
    TemplateId string `json:"templateId"`
}