// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type UnreleasedSc struct {

    /* 类型  1:可一键处理 2:需手动处理 (Optional) */
    AccessType int `json:"accessType"`

    /* 产品编码 (Optional) */
    ServiceCode string `json:"serviceCode"`

    /* 产品名称 (Optional) */
    ServiceCodeName string `json:"serviceCodeName"`

    /* 描述 (Optional) */
    Desc string `json:"desc"`

    /* 控制台链接 (Optional) */
    ScUrl string `json:"scUrl"`

    /* 实例数量 (Optional) */
    ResourceCount string `json:"resourceCount"`
}
