// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type RespQueryTemplateListData struct {

    /* 短信ID (Optional) */
    TemplateId string `json:"templateId"`

    /* 短信标题 (Optional) */
    Title string `json:"title"`

    /* 审核状态 0: 审核中 1: 通过 2: 未通过 4:待提交 (Optional) */
    Status string `json:"status"`

    /* 审核未通过原因 (Optional) */
    Reason string `json:"reason"`

    /* 短信创建时间 yyyy-MM-dd HH:mm:ss (Optional) */
    CreateTime string `json:"createTime"`

    /* 短信内容大小 (Optional) */
    ContentSize string `json:"contentSize"`

    /* 资质Id (Optional) */
    AptitudesId string `json:"aptitudesId"`

    /* 短信描述 (Optional) */
    Description string `json:"description"`
}
