// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type BuffaloDependencyUpdateRecordForDescribeBuffaloDependencyUpdateRecords struct {

    /* 本次批量操作ID。 (Optional) */
    OperationId string `json:"operationId"`

    /* 记录所属工作空间ID。 (Optional) */
    WorkspaceId string `json:"workspaceId"`

    /* 任务定义ID。 (Optional) */
    JobDefinitionId string `json:"jobDefinitionId"`

    /* 任务定义名称。 (Optional) */
    JobDefinitionName string `json:"jobDefinitionName"`

    /* 本次删除的原父 Buffalo 任务ID。 (Optional) */
    SourceBuffaloId int64 `json:"sourceBuffaloId"`

    /* 本次删除的原父 Buffalo 任务名称快照。 (Optional) */
    SourceBuffaloName string `json:"sourceBuffaloName"`

    /* 本次新增的目标父 Buffalo 任务ID。 (Optional) */
    TargetBuffaloId int64 `json:"targetBuffaloId"`

    /* 本次新增的目标父 Buffalo 任务名称快照。 (Optional) */
    TargetBuffaloName string `json:"targetBuffaloName"`

    /* 下游 Buffalo 任务ID。 (Optional) */
    DownstreamBuffaloId int64 `json:"downstreamBuffaloId"`

    /* 下游 Buffalo 任务名称快照。 (Optional) */
    DownstreamBuffaloName string `json:"downstreamBuffaloName"`

    /* 下游 Buffalo 任务负责人账号快照。 (Optional) */
    DownstreamManagers string `json:"downstreamManagers"`

    /* 下游 Buffalo 任务负责人名称快照。 (Optional) */
    DownstreamManagersName string `json:"downstreamManagersName"`

    /* 操作类型。可选值：`switch`、`rollback`。 (Optional) */
    OperationType string `json:"operationType"`

    /* 更新状态。可选值：`success`、`failed`。 (Optional) */
    UpdateStatus string `json:"updateStatus"`

    /* 可直接展示的更新结果摘要，不包含内部审计 JSON。 (Optional) */
    ResultDetail string `json:"resultDetail"`

    /* 操作人ID。 (Optional) */
    OperatorUserId string `json:"operatorUserId"`

    /* 操作人名称。 (Optional) */
    OperatorUserName string `json:"operatorUserName"`

    /* 操作开始时间，北京时间，格式为 yyyy-MM-dd HH:mm:ss。 (Optional) */
    CreateTime string `json:"createTime"`

    /* 操作完成时间，北京时间，格式为 yyyy-MM-dd HH:mm:ss；页面时间列使用该字段。 (Optional) */
    FinishTime string `json:"finishTime"`
}
