// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type CreateCodeRepoConfigParam struct {

    /* 代码库配置名称（1~64字符，仅支持中文、大小写字母、数字、英文中划线“-”、英文下划线“_”和点 “.”） (Optional) */
    RepoName *string `json:"repoName"`

    /* 代码库类型，可选值：GitHub、Coding (Optional) */
    RepoType *string `json:"repoType"`

    /* 描述 (Optional) */
    Description *string `json:"description"`

    /* Coding的projectId（repoType=Coding时使用且必填） (Optional) */
    ProjectId *string `json:"projectId"`

    /* 代码库地址（repoType=GitHub时使用且必填） (Optional) */
    Url *string `json:"url"`

    /* 代码库分支（commit为空时必填） (Optional) */
    Branch *string `json:"branch"`

    /* 代码库commint（branch为空时必填） (Optional) */
    Commit *string `json:"commit"`

    /* git用户名 (Optional) */
    Username *string `json:"username"`

    /* git访问凭证 (Optional) */
    AccessToken *string `json:"accessToken"`

    /* 工作空间中的资源归属权限，支持(public,private)，默认为public。 (Optional) */
    Permission *string `json:"permission"`
}
