// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type FinetuningConfigParamForExperiment struct {

    /* 训练阶段。

## 可选值
- `pt`：预训练
- `sft`：有监督微调
- `dpo`：直接偏好优化

## 默认
建议使用 `sft` 进行微调。
 (Optional) */
    Stage *string `json:"stage"`

    /* 微调方法。

## 可选值
- `lora`：低秩适配，推荐使用
- `full`：全量微调

## 建议
`lora` 方法在保持效果的同时大幅降低资源消耗。
 (Optional) */
    FinetuningType *string `json:"finetuningType"`

    /* 微调运行额外配置参数。

用于自定义训练参数，如学习率、批次大小等。
 (Optional) */
    RunConfigExtras []RunConfigExtraParamForExperiment `json:"runConfigExtras"`
}
