// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type InferenceDedicatedGatewaySpec struct {

    /* 专属网关实例数, 大于等于1，默认为2， 为安全起见，建议最少为2 (Optional) */
    Replicas int `json:"replicas"`

    /* 专属网关单个实例所需cpu资源，单位豪核 如： 1000是一核 (Optional) */
    Cpu int `json:"cpu"`

    /* 专属网关单个实例所需内存资源，单位M， 如： 1024是1G (Optional) */
    Memory int `json:"memory"`

    /* 是否仅内网可用；`true` 表示只提供内网地址 (Optional) */
    Internal bool `json:"internal"`

    /* 专属网关所属vpc (Optional) */
    Vpc Vpc `json:"vpc"`

    /* 子网信息  */
    Subnet Subnet `json:"subnet"`

    /* 公网信息 (Optional) */
    ElasticIp ElasticIp `json:"elasticIp"`

    /* 可用区集合（逗号分隔）  */
    Azs []Az `json:"azs"`

    /* 自建LB保留策略，默认 `false`；为 `true` 时在删除网关时仅删除LB下配置，保留LB及公网IP（仅对自建LB生效） (Optional) */
    Retain bool `json:"retain"`

    /* EIP 回收策略，`delete|retain`，默认 `delete`；当未指定 `elasticIpId` 且创建公网 EIP 时生效 (Optional) */
    ReclaimPolicy string `json:"reclaimPolicy"`
}
