// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type NbModelDetail struct {

    /* 模型来源，指定模型是公共的还是个人的。

## 来源类型
- public: 公共模型，所有用户可访问
- self: 个人模型，仅自己可访问
 (Optional) */
    Source string `json:"source"`

    /* 存储名称，模型对应的存储名称。 (Optional) */
    StorageName string `json:"storageName"`

    /* 存储类型，模型的存储后端类型。

## 支持类型
- cfs: 京东云文件存储
- oss: 京东云对象存储
- jpfs: 京东云并行文件系统
 (Optional) */
    StorageType string `json:"storageType"`

    /* 模型ID，唯一标识模型。 (Optional) */
    ModelId string `json:"modelId"`

    /* 模型版本，指定的模型版本号。 (Optional) */
    ModelVersion string `json:"modelVersion"`

    /* 模型地址，模型的实际存储路径。

## 各类型地址格式
- cfs: `10.0.23.45:/dir-path` 或 `/dir-path`
- oss: `oss://bucket.s3.cn-north-1.jdcloud-oss.com/object-path`
- jpfs: `fs-xxxxxxxxxx:/dir-path` 或 `/dir-path`
 (Optional) */
    ModelUrl string `json:"modelUrl"`

    /* 挂载路径，模型在Notebook容器中的挂载位置。

## 挂载建议
- 建议挂载到`/mnt/models/`开头的路径
 (Optional) */
    MountPath string `json:"mountPath"`

    /* 是否以只读模式挂载模型。

## 使用说明
- 仅oss类型且self来源的模型有效
- public模型强制只读
- true: 只读模式，无法写入
- false: 读写模式，可读写
 (Optional) */
    Readonly bool `json:"readonly"`
}
