// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type NodePoolOverviewQuantity3J struct {

    /* 总量；页面“虚拟化显卡数量(已分配/总量)”的总量使用 virtualGpus.total (Optional) */
    Total float32 `json:"total"`

    /* 已分配数量；页面“虚拟化显卡数量(已分配/总量)”的已分配使用 virtualGpus.allocated (Optional) */
    Allocated float32 `json:"allocated"`
}
