// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type ResFlavor struct {

    /* 分类。 范围：cpu：cpu规格，gpu：gpu规格 (Optional) */
    Category string `json:"category"`

    /* 规格id (Optional) */
    FlavorId string `json:"flavorId"`

    /* 规格名称 (Optional) */
    FlavorName string `json:"flavorName"`

    /* cpu数量 单位：毫核 (Optional) */
    CpuM int `json:"cpuM"`

    /* 内存大小 单位：MiB (Optional) */
    MemoryMiB int `json:"memoryMiB"`

    /* gpu规格 (Optional) */
    Gpu Gpu `json:"gpu"`

    /* RDMA规格 (Optional) */
    Rdma Rdma `json:"rdma"`
}
