// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type VPCInfo struct {

    /* 如果用户希望vpc ip复用alb，此处传入复用的alb id (Optional) */
    AlbId *string `json:"albId"`

    /* true:表示alb是复用; false:alb新建 (Optional) */
    AlbReuse *bool `json:"albReuse"`

    /* 用户指定alb监听端口 (Optional) */
    ListenPort *int `json:"listenPort"`

    /* 是否开启vpc访问 (Optional) */
    VpcAccess *bool `json:"vpcAccess"`

    /* vpc ip所属的子网id (Optional) */
    SubnetId *string `json:"subnetId"`

    /* vpc ip支持的协议, 如，HTTP, Grpc, UDP or TCP (Optional) */
    VpcProto *string `json:"vpcProto"`

    /* 协议层, 7 or 4 (Optional) */
    ProtoLevel *int `json:"protoLevel"`
}
