// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type ServiceLevels struct {

    /*  (Optional) */
    Jdc_ent string `json:"jdc_ent"`

    /*  (Optional) */
    Jdc_pro string `json:"jdc_pro"`

    /*  (Optional) */
    Jdc_free string `json:"jdc_free"`

    /*  (Optional) */
    Jdc_basic string `json:"jdc_basic"`

    /*  (Optional) */
    Jdc_flagship string `json:"jdc_flagship"`
}
