// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type NodeSpecDTO struct {

    /* 实例规格（如：g.n1.medium） (Optional) */
    NodeSpec string `json:"nodeSpec"`

    /* CPU核数 (Optional) */
    Cpu int `json:"cpu"`

    /* 内存大小（GB） (Optional) */
    Mem int `json:"mem"`

    /* GPU信息（如：A100-40G-2） (Optional) */
    Gpu string `json:"gpu"`

    /* 本地数据盘信息（来源于sys_disk字段） (Optional) */
    LocalDisks string `json:"localDisks"`

    /* 节点类型（cpu/gpu） (Optional) */
    NodeType string `json:"nodeType"`

    /* 节点类型（vm/hpc，可选过滤条件，不传则查全部） (Optional) */
    NodeCategory string `json:"nodeCategory"`
}
