// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type URLRuleConfigObject struct {

    /* 鉴权类型。取值范围：
  by_params - 参数鉴权
  by_path - 路径鉴权
  */
    AuthType string `json:"authType"`

    /* 鉴权密钥  */
    AuthKey string `json:"authKey"`
}
