// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    captcha "github.com/jdcloud-api/jdcloud-sdk-go/services/captcha/models"
)

type VerifyTokenRequest struct {

    core.JDCloudRequest

    /* 提交后台校验的token，客户端sdk获取 (Optional) */
    VerifyToken *string `json:"verifyToken"`

    /* 验证码会话id，getsessionid返回 (Optional) */
    SessionId *string `json:"sessionId"`

    /* 应用id (Optional) */
    AppId *int64 `json:"appId"`

    /* 场景id (Optional) */
    SceneId *int64 `json:"sceneId"`

    /* 密钥，从界面获取 (Optional) */
    Secret *string `json:"secret"`

    /* 客户端ip (Optional) */
    Ip *string `json:"ip"`

    /* 客户端userAgent (Optional) */
    UserAgent *string `json:"userAgent"`

    /* 客户端类型, 可选值: android, ios, pc, wxapp, m (Optional) */
    ClientType *string `json:"clientType"`

    /* 客户端版本，用户端app版本，可选 (Optional) */
    ClientVersion *string `json:"clientVersion"`
}

/*
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewVerifyTokenRequest(
) *VerifyTokenRequest {

	return &VerifyTokenRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/captcha:verifytoken",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
	}
}

/*
 * param verifyToken: 提交后台校验的token，客户端sdk获取 (Optional)
 * param sessionId: 验证码会话id，getsessionid返回 (Optional)
 * param appId: 应用id (Optional)
 * param sceneId: 场景id (Optional)
 * param secret: 密钥，从界面获取 (Optional)
 * param ip: 客户端ip (Optional)
 * param userAgent: 客户端userAgent (Optional)
 * param clientType: 客户端类型, 可选值: android, ios, pc, wxapp, m (Optional)
 * param clientVersion: 客户端版本，用户端app版本，可选 (Optional)
 */
func NewVerifyTokenRequestWithAllParams(
    verifyToken *string,
    sessionId *string,
    appId *int64,
    sceneId *int64,
    secret *string,
    ip *string,
    userAgent *string,
    clientType *string,
    clientVersion *string,
) *VerifyTokenRequest {

    return &VerifyTokenRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/captcha:verifytoken",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        VerifyToken: verifyToken,
        SessionId: sessionId,
        AppId: appId,
        SceneId: sceneId,
        Secret: secret,
        Ip: ip,
        UserAgent: userAgent,
        ClientType: clientType,
        ClientVersion: clientVersion,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewVerifyTokenRequestWithoutParam() *VerifyTokenRequest {

    return &VerifyTokenRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/captcha:verifytoken",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param verifyToken: 提交后台校验的token，客户端sdk获取(Optional) */
func (r *VerifyTokenRequest) SetVerifyToken(verifyToken string) {
    r.VerifyToken = &verifyToken
}

/* param sessionId: 验证码会话id，getsessionid返回(Optional) */
func (r *VerifyTokenRequest) SetSessionId(sessionId string) {
    r.SessionId = &sessionId
}

/* param appId: 应用id(Optional) */
func (r *VerifyTokenRequest) SetAppId(appId int64) {
    r.AppId = &appId
}

/* param sceneId: 场景id(Optional) */
func (r *VerifyTokenRequest) SetSceneId(sceneId int64) {
    r.SceneId = &sceneId
}

/* param secret: 密钥，从界面获取(Optional) */
func (r *VerifyTokenRequest) SetSecret(secret string) {
    r.Secret = &secret
}

/* param ip: 客户端ip(Optional) */
func (r *VerifyTokenRequest) SetIp(ip string) {
    r.Ip = &ip
}

/* param userAgent: 客户端userAgent(Optional) */
func (r *VerifyTokenRequest) SetUserAgent(userAgent string) {
    r.UserAgent = &userAgent
}

/* param clientType: 客户端类型, 可选值: android, ios, pc, wxapp, m(Optional) */
func (r *VerifyTokenRequest) SetClientType(clientType string) {
    r.ClientType = &clientType
}

/* param clientVersion: 客户端版本，用户端app版本，可选(Optional) */
func (r *VerifyTokenRequest) SetClientVersion(clientVersion string) {
    r.ClientVersion = &clientVersion
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r VerifyTokenRequest) GetRegionId() string {
    return ""
}

type VerifyTokenResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result VerifyTokenResult `json:"result"`
}

type VerifyTokenResult struct {
    Data captcha.VerifyDataResp `json:"data"`
}