// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/lshuining/jdcloud-sdk-go/core"
)

type DescribeStatusGraphRequest struct {

    core.JDCloudRequest

    /* 区域 ID, 高防不区分区域, 传 cn-north-1 即可  */
    RegionId string `json:"regionId"`

    /* 开始时间, 只能查询最近 7 天以内的数据, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ  */
    StartTime string `json:"startTime"`

    /* 查询的结束时间, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ (Optional) */
    EndTime *string `json:"endTime"`

    /* 高防实例 Id 列表 (Optional) */
    InstanceId []string `json:"instanceId"`

    /* 规则域名列表 (Optional) */
    SubDomain []string `json:"subDomain"`
}

/*
 * param regionId: 区域 ID, 高防不区分区域, 传 cn-north-1 即可 (Required)
 * param startTime: 开始时间, 只能查询最近 7 天以内的数据, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDescribeStatusGraphRequest(
    regionId string,
    startTime string,
) *DescribeStatusGraphRequest {

	return &DescribeStatusGraphRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/charts:statusGraph",
			Method:  "GET",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        StartTime: startTime,
	}
}

/*
 * param regionId: 区域 ID, 高防不区分区域, 传 cn-north-1 即可 (Required)
 * param startTime: 开始时间, 只能查询最近 7 天以内的数据, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ (Required)
 * param endTime: 查询的结束时间, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ (Optional)
 * param instanceId: 高防实例 Id 列表 (Optional)
 * param subDomain: 规则域名列表 (Optional)
 */
func NewDescribeStatusGraphRequestWithAllParams(
    regionId string,
    startTime string,
    endTime *string,
    instanceId []string,
    subDomain []string,
) *DescribeStatusGraphRequest {

    return &DescribeStatusGraphRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/charts:statusGraph",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        StartTime: startTime,
        EndTime: endTime,
        InstanceId: instanceId,
        SubDomain: subDomain,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDescribeStatusGraphRequestWithoutParam() *DescribeStatusGraphRequest {

    return &DescribeStatusGraphRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/charts:statusGraph",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 区域 ID, 高防不区分区域, 传 cn-north-1 即可(Required) */
func (r *DescribeStatusGraphRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}

/* param startTime: 开始时间, 只能查询最近 7 天以内的数据, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ(Required) */
func (r *DescribeStatusGraphRequest) SetStartTime(startTime string) {
    r.StartTime = startTime
}

/* param endTime: 查询的结束时间, UTC 时间, 格式: yyyy-MM-dd'T'HH:mm:ssZ(Optional) */
func (r *DescribeStatusGraphRequest) SetEndTime(endTime string) {
    r.EndTime = &endTime
}

/* param instanceId: 高防实例 Id 列表(Optional) */
func (r *DescribeStatusGraphRequest) SetInstanceId(instanceId []string) {
    r.InstanceId = instanceId
}

/* param subDomain: 规则域名列表(Optional) */
func (r *DescribeStatusGraphRequest) SetSubDomain(subDomain []string) {
    r.SubDomain = subDomain
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DescribeStatusGraphRequest) GetRegionId() string {
    return r.RegionId
}

type DescribeStatusGraphResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DescribeStatusGraphResult `json:"result"`
}

type DescribeStatusGraphResult struct {
    Status500 []int64 `json:"status500"`
    Status502 []int64 `json:"status502"`
    Status504 []int64 `json:"status504"`
    Status590 []int64 `json:"status590"`
    Status592 []int64 `json:"status592"`
    Status594 []int64 `json:"status594"`
    Status5xx []int64 `json:"status5xx"`
    Time []string `json:"time"`
}