// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type PostAddress struct {

    /* id (Optional) */
    Id int `json:"id"`

    /* 收件人姓名 (Optional) */
    Name string `json:"name"`

    /* 收件人电话 (Optional) */
    Phone string `json:"phone"`

    /* 省 (Optional) */
    Province string `json:"province"`

    /* 市 (Optional) */
    City string `json:"city"`

    /* 区 (Optional) */
    County string `json:"county"`

    /* 县 (Optional) */
    Town string `json:"town"`

    /* 邮编 (Optional) */
    Address string `json:"address"`

    /* 是否默认收货地址 (Optional) */
    IsDefault int `json:"isDefault"`

    /* 更新时间 (Optional) */
    UpdateTime string `json:"updateTime"`

    /* 用户pin (Optional) */
    Pin string `json:"pin"`

    /* 创建时间 (Optional) */
    CreateTime string `json:"createTime"`

    /* 邮编 (Optional) */
    ZipCode string `json:"zipCode"`

    /* 省id (Optional) */
    ProvinceId int `json:"provinceId"`

    /* 市id (Optional) */
    CityId int `json:"cityId"`

    /* 区县id (Optional) */
    CountyId int `json:"countyId"`

    /* 乡镇id (Optional) */
    TownId int `json:"townId"`
}
