// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    rocketmq "github.com/jdcloud-api/jdcloud-sdk-go/services/rocketmq/models"
)

type DescribeConsumerGroupStatusRequest struct {

    core.JDCloudRequest

    /* 区域ID  */
    RegionId string `json:"regionId"`

    /* 实例id  */
    InstanceId string `json:"instanceId"`

    /* 消费组名称  */
    ConsumerGroup string `json:"consumerGroup"`
}

/*
 * param regionId: 区域ID (Required)
 * param instanceId: 实例id (Required)
 * param consumerGroup: 消费组名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDescribeConsumerGroupStatusRequest(
    regionId string,
    instanceId string,
    consumerGroup string,
) *DescribeConsumerGroupStatusRequest {

	return &DescribeConsumerGroupStatusRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/instances/{instanceId}/consumerGroups/{consumerGroup}/status",
			Method:  "GET",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        InstanceId: instanceId,
        ConsumerGroup: consumerGroup,
	}
}

/*
 * param regionId: 区域ID (Required)
 * param instanceId: 实例id (Required)
 * param consumerGroup: 消费组名称 (Required)
 */
func NewDescribeConsumerGroupStatusRequestWithAllParams(
    regionId string,
    instanceId string,
    consumerGroup string,
) *DescribeConsumerGroupStatusRequest {

    return &DescribeConsumerGroupStatusRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/instances/{instanceId}/consumerGroups/{consumerGroup}/status",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        InstanceId: instanceId,
        ConsumerGroup: consumerGroup,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDescribeConsumerGroupStatusRequestWithoutParam() *DescribeConsumerGroupStatusRequest {

    return &DescribeConsumerGroupStatusRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/instances/{instanceId}/consumerGroups/{consumerGroup}/status",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 区域ID(Required) */
func (r *DescribeConsumerGroupStatusRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param instanceId: 实例id(Required) */
func (r *DescribeConsumerGroupStatusRequest) SetInstanceId(instanceId string) {
    r.InstanceId = instanceId
}
/* param consumerGroup: 消费组名称(Required) */
func (r *DescribeConsumerGroupStatusRequest) SetConsumerGroup(consumerGroup string) {
    r.ConsumerGroup = consumerGroup
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DescribeConsumerGroupStatusRequest) GetRegionId() string {
    return r.RegionId
}

type DescribeConsumerGroupStatusResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DescribeConsumerGroupStatusResult `json:"result"`
}

type DescribeConsumerGroupStatusResult struct {
    ConsumerGroupStatus rocketmq.ConsumerGroupStatus `json:"consumerGroupStatus"`
}