// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type AttachSubUserPolicyRequest struct {

    core.JDCloudRequest

    /* 子用户名  */
    SubUser string `json:"subUser"`

    /* 策略名称  */
    PolicyName string `json:"policyName"`

    /* 资源组id (Optional) */
    ScopeId *string `json:"scopeId"`

    /* 允许添加策略绑定："Deny" 不允许，Allow 允许，空情况默认允许，兼容历史数据 (Optional) */
    AllowAddPolicy *string `json:"allowAddPolicy"`
}

/*
 * param subUser: 子用户名 (Required)
 * param policyName: 策略名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewAttachSubUserPolicyRequest(
    subUser string,
    policyName string,
) *AttachSubUserPolicyRequest {

	return &AttachSubUserPolicyRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/subUser/{subUser}:attachSubUserPolicy",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        SubUser: subUser,
        PolicyName: policyName,
	}
}

/*
 * param subUser: 子用户名 (Required)
 * param policyName: 策略名称 (Required)
 * param scopeId: 资源组id (Optional)
 * param allowAddPolicy: 允许添加策略绑定："Deny" 不允许，Allow 允许，空情况默认允许，兼容历史数据 (Optional)
 */
func NewAttachSubUserPolicyRequestWithAllParams(
    subUser string,
    policyName string,
    scopeId *string,
    allowAddPolicy *string,
) *AttachSubUserPolicyRequest {

    return &AttachSubUserPolicyRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/subUser/{subUser}:attachSubUserPolicy",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        SubUser: subUser,
        PolicyName: policyName,
        ScopeId: scopeId,
        AllowAddPolicy: allowAddPolicy,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewAttachSubUserPolicyRequestWithoutParam() *AttachSubUserPolicyRequest {

    return &AttachSubUserPolicyRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/subUser/{subUser}:attachSubUserPolicy",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param subUser: 子用户名(Required) */
func (r *AttachSubUserPolicyRequest) SetSubUser(subUser string) {
    r.SubUser = subUser
}
/* param policyName: 策略名称(Required) */
func (r *AttachSubUserPolicyRequest) SetPolicyName(policyName string) {
    r.PolicyName = policyName
}
/* param scopeId: 资源组id(Optional) */
func (r *AttachSubUserPolicyRequest) SetScopeId(scopeId string) {
    r.ScopeId = &scopeId
}
/* param allowAddPolicy: 允许添加策略绑定："Deny" 不允许，Allow 允许，空情况默认允许，兼容历史数据(Optional) */
func (r *AttachSubUserPolicyRequest) SetAllowAddPolicy(allowAddPolicy string) {
    r.AllowAddPolicy = &allowAddPolicy
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r AttachSubUserPolicyRequest) GetRegionId() string {
    return ""
}

type AttachSubUserPolicyResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result AttachSubUserPolicyResult `json:"result"`
}

type AttachSubUserPolicyResult struct {
}