// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/lshuining/jdcloud-sdk-go/core"
)

type DetachGroupPolicyRequest struct {

    core.JDCloudRequest

    /* 用户组名称  */
    GroupName string `json:"groupName"`

    /* 策略名称  */
    PolicyName string `json:"policyName"`
}

/*
 * param groupName: 用户组名称 (Required)
 * param policyName: 策略名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDetachGroupPolicyRequest(
    groupName string,
    policyName string,
) *DetachGroupPolicyRequest {

	return &DetachGroupPolicyRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/group/{groupName}:detachGroupPolicy",
			Method:  "DELETE",
			Header:  nil,
			Version: "v1",
		},
        GroupName: groupName,
        PolicyName: policyName,
	}
}

/*
 * param groupName: 用户组名称 (Required)
 * param policyName: 策略名称 (Required)
 */
func NewDetachGroupPolicyRequestWithAllParams(
    groupName string,
    policyName string,
) *DetachGroupPolicyRequest {

    return &DetachGroupPolicyRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/group/{groupName}:detachGroupPolicy",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
        GroupName: groupName,
        PolicyName: policyName,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDetachGroupPolicyRequestWithoutParam() *DetachGroupPolicyRequest {

    return &DetachGroupPolicyRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/group/{groupName}:detachGroupPolicy",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param groupName: 用户组名称(Required) */
func (r *DetachGroupPolicyRequest) SetGroupName(groupName string) {
    r.GroupName = groupName
}

/* param policyName: 策略名称(Required) */
func (r *DetachGroupPolicyRequest) SetPolicyName(policyName string) {
    r.PolicyName = policyName
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DetachGroupPolicyRequest) GetRegionId() string {
    return ""
}

type DetachGroupPolicyResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DetachGroupPolicyResult `json:"result"`
}

type DetachGroupPolicyResult struct {
}