// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type DiagnosticResultDetail struct {

    /* 诊断任务ID。 (Optional) */
    DiagnosticId string `json:"diagnosticId"`

    /* 诊断目标节点ID列表。 (Optional) */
    NodeIds []string `json:"nodeIds"`

    /* 集群ID。 (Optional) */
    ClusterId string `json:"clusterId"`

    /* 诊断类型。 (Optional) */
    DiagnosticType string `json:"diagnosticType"`

    /* 诊断任务状态。 (Optional) */
    DiagnosticState string `json:"diagnosticState"`

    /* 诊断结果详情。
返回结构为动态对象，不同 `diagnosticType` 的结构可能不同。

当 `diagnosticType` 为 `HPCHealthCheck` 时，返回结构为：
- 顶层为按节点分组的对象（`key` 为节点ID，通常对应 `resourceId`）。
- 每个节点对应一个结果数组，数组元素对象包含以下字段：
  - `serialNumber`：序号（integer）
  - `diagnosticItem`：诊断项名称（string）
  - `diagnosticResult`：诊断结论（string）
  - `description`：诊断项描述（string）
  - `node`：节点ID（string）
  - `checkValue`：检测值（任意类型）
  - `diagnosticStatus`：诊断状态（string）
    - 枚举值：`pass`、`failed`、`ok`、`诊断通过`、`诊断失败`
    - 说明：若配置了状态映射规则，可能返回中文映射值（如 `诊断通过`）

示例：
{
  "node-1": [
    {
      "serialNumber": 1,
      "diagnosticItem": "GPU",
      "diagnosticResult": "所有的GPU在线",
      "description": "GPU 在线检查",
      "node": "node-1",
      "checkValue": 8,
      "diagnosticStatus": "诊断通过"
    }
  ]
}
 (Optional) */
    DiagnosticResults interface{} `json:"diagnosticResults"`

    /* 创建时间，RFC3339 格式（UTC+8）。 (Optional) */
    CreatedTime string `json:"createdTime"`

    /* 结束时间，RFC3339 格式（UTC+8）。 (Optional) */
    EndTime string `json:"endTime"`
}
