// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type ReleaseNatIpsRequest struct {

    core.JDCloudRequest

    /* Region ID  */
    RegionId string `json:"regionId"`

    /* natGateway ID  */
    NatGatewayId string `json:"natGatewayId"`

    /* NAT IP ID 列表。单次请求数量不能超过100个  */
    NatIpIds []string `json:"natIpIds"`
}

/*
 * param regionId: Region ID (Required)
 * param natGatewayId: natGateway ID (Required)
 * param natIpIds: NAT IP ID 列表。单次请求数量不能超过100个 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewReleaseNatIpsRequest(
    regionId string,
    natGatewayId string,
    natIpIds []string,
) *ReleaseNatIpsRequest {

	return &ReleaseNatIpsRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/natGateways/{natGatewayId}/natIps:releaseNatIps",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        NatGatewayId: natGatewayId,
        NatIpIds: natIpIds,
	}
}

/*
 * param regionId: Region ID (Required)
 * param natGatewayId: natGateway ID (Required)
 * param natIpIds: NAT IP ID 列表。单次请求数量不能超过100个 (Required)
 */
func NewReleaseNatIpsRequestWithAllParams(
    regionId string,
    natGatewayId string,
    natIpIds []string,
) *ReleaseNatIpsRequest {

    return &ReleaseNatIpsRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/natGateways/{natGatewayId}/natIps:releaseNatIps",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        NatGatewayId: natGatewayId,
        NatIpIds: natIpIds,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewReleaseNatIpsRequestWithoutParam() *ReleaseNatIpsRequest {

    return &ReleaseNatIpsRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/natGateways/{natGatewayId}/natIps:releaseNatIps",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: Region ID(Required) */
func (r *ReleaseNatIpsRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param natGatewayId: natGateway ID(Required) */
func (r *ReleaseNatIpsRequest) SetNatGatewayId(natGatewayId string) {
    r.NatGatewayId = natGatewayId
}
/* param natIpIds: NAT IP ID 列表。单次请求数量不能超过100个(Required) */
func (r *ReleaseNatIpsRequest) SetNatIpIds(natIpIds []string) {
    r.NatIpIds = natIpIds
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r ReleaseNatIpsRequest) GetRegionId() string {
    return r.RegionId
}

type ReleaseNatIpsResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result ReleaseNatIpsResult `json:"result"`
}

type ReleaseNatIpsResult struct {
}