// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type DeleteNotebookRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 工作空间ID  */
    WorkspaceId string `json:"workspaceId"`

    /* notebook ID  */
    NotebookId string `json:"notebookId"`
}

/*
 * param regionId: 地域ID (Required)
 * param workspaceId: 工作空间ID (Required)
 * param notebookId: notebook ID (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDeleteNotebookRequest(
    regionId string,
    workspaceId string,
    notebookId string,
) *DeleteNotebookRequest {

	return &DeleteNotebookRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/nb-regions/{regionId}/workspace/{workspaceId}/notebook/{notebookId}",
			Method:  "DELETE",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        WorkspaceId: workspaceId,
        NotebookId: notebookId,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param workspaceId: 工作空间ID (Required)
 * param notebookId: notebook ID (Required)
 */
func NewDeleteNotebookRequestWithAllParams(
    regionId string,
    workspaceId string,
    notebookId string,
) *DeleteNotebookRequest {

    return &DeleteNotebookRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/nb-regions/{regionId}/workspace/{workspaceId}/notebook/{notebookId}",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        WorkspaceId: workspaceId,
        NotebookId: notebookId,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDeleteNotebookRequestWithoutParam() *DeleteNotebookRequest {

    return &DeleteNotebookRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/nb-regions/{regionId}/workspace/{workspaceId}/notebook/{notebookId}",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *DeleteNotebookRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param workspaceId: 工作空间ID(Required) */
func (r *DeleteNotebookRequest) SetWorkspaceId(workspaceId string) {
    r.WorkspaceId = workspaceId
}
/* param notebookId: notebook ID(Required) */
func (r *DeleteNotebookRequest) SetNotebookId(notebookId string) {
    r.NotebookId = notebookId
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DeleteNotebookRequest) GetRegionId() string {
    return r.RegionId
}

type DeleteNotebookResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DeleteNotebookResult `json:"result"`
}

type DeleteNotebookResult struct {
}