// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type UnbindWorkspaceResourcesRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 工作空间ID  */
    WorkspaceId string `json:"workspaceId"`

    /* 要解绑的资源类型  */
    ResourceType string `json:"resourceType"`

    /* 要解绑资源类型的主键值，支持多个使用","分隔，最多20个  */
    ResourceIdVals string `json:"resourceIdVals"`
}

/*
 * param regionId: 地域ID (Required)
 * param workspaceId: 工作空间ID (Required)
 * param resourceType: 要解绑的资源类型 (Required)
 * param resourceIdVals: 要解绑资源类型的主键值，支持多个使用","分隔，最多20个 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewUnbindWorkspaceResourcesRequest(
    regionId string,
    workspaceId string,
    resourceType string,
    resourceIdVals string,
) *UnbindWorkspaceResourcesRequest {

	return &UnbindWorkspaceResourcesRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/ws-regions/{regionId}/workspace/{workspaceId}/resources",
			Method:  "DELETE",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        WorkspaceId: workspaceId,
        ResourceType: resourceType,
        ResourceIdVals: resourceIdVals,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param workspaceId: 工作空间ID (Required)
 * param resourceType: 要解绑的资源类型 (Required)
 * param resourceIdVals: 要解绑资源类型的主键值，支持多个使用","分隔，最多20个 (Required)
 */
func NewUnbindWorkspaceResourcesRequestWithAllParams(
    regionId string,
    workspaceId string,
    resourceType string,
    resourceIdVals string,
) *UnbindWorkspaceResourcesRequest {

    return &UnbindWorkspaceResourcesRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/ws-regions/{regionId}/workspace/{workspaceId}/resources",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        WorkspaceId: workspaceId,
        ResourceType: resourceType,
        ResourceIdVals: resourceIdVals,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewUnbindWorkspaceResourcesRequestWithoutParam() *UnbindWorkspaceResourcesRequest {

    return &UnbindWorkspaceResourcesRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/ws-regions/{regionId}/workspace/{workspaceId}/resources",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *UnbindWorkspaceResourcesRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param workspaceId: 工作空间ID(Required) */
func (r *UnbindWorkspaceResourcesRequest) SetWorkspaceId(workspaceId string) {
    r.WorkspaceId = workspaceId
}
/* param resourceType: 要解绑的资源类型(Required) */
func (r *UnbindWorkspaceResourcesRequest) SetResourceType(resourceType string) {
    r.ResourceType = resourceType
}
/* param resourceIdVals: 要解绑资源类型的主键值，支持多个使用","分隔，最多20个(Required) */
func (r *UnbindWorkspaceResourcesRequest) SetResourceIdVals(resourceIdVals string) {
    r.ResourceIdVals = resourceIdVals
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r UnbindWorkspaceResourcesRequest) GetRegionId() string {
    return r.RegionId
}

type UnbindWorkspaceResourcesResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result UnbindWorkspaceResourcesResult `json:"result"`
}

type UnbindWorkspaceResourcesResult struct {
}