// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type BackupSnapshotRestoreLogRes struct {

    /* 恢复记录ID (Optional) */
    Id int64 `json:"id"`

    /* 实例code (Optional) */
    ProjectCode string `json:"projectCode"`

    /* 备份仓库名称 (Optional) */
    RepoName string `json:"repoName"`

    /* 恢复数据库名称 (Optional) */
    DbName string `json:"dbName"`

    /* 恢复快照名称 (Optional) */
    SnapshotName string `json:"snapshotName"`

    /* 恢复快照时间戳 (Optional) */
    SnapshotTimestamp string `json:"snapshotTimestamp"`

    /* 副本数 (Optional) */
    ReplicaNum int `json:"replicaNum"`

    /* 恢复内容详情（json字符串） (Optional) */
    RestoreContent string `json:"restoreContent"`

    /* 创建人 (Optional) */
    Creator string `json:"creator"`

    /* 创建时间 (Optional) */
    CreateTime string `json:"createTime"`

    /* 上次扫描时间 (Optional) */
    LastScanTime string `json:"lastScanTime"`

    /* 恢复开始时间 (Optional) */
    StartTime string `json:"startTime"`

    /* 恢复结束时间 (Optional) */
    EndTime string `json:"endTime"`

    /* 恢复状态 (Optional) */
    Status string `json:"status"`

    /* 恢复失败原因 (Optional) */
    ErrMsg string `json:"errMsg"`
}
