// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type SetPinCode struct {

    /* 用户ID,新增时为0，更新时为更新id值 (Optional) */
    Id int `json:"id"`

    /* 用户pin (Optional) */
    UserPin string `json:"userPin"`

    /* 客户编码 (Optional) */
    CustomerCode string `json:"customerCode"`

    /* 业务线编码 (Optional) */
    ServiceCode string `json:"serviceCode"`

    /* 注册策略编码 (Optional) */
    SignupStgyCode string `json:"signupStgyCode"`

    /* 登录策略编码 (Optional) */
    LoginStgyCode string `json:"loginStgyCode"`

    /* 营销策略编码 (Optional) */
    MarketingStgyCode string `json:"marketingStgyCode"`

    /* 注册杰夫分组 (Optional) */
    SignupJsfCode string `json:"signupJsfCode"`

    /* 登录杰夫分组 (Optional) */
    LoginJsfCode string `json:"loginJsfCode"`

    /* 营销杰夫分组 (Optional) */
    MarketingJsfCode string `json:"marketingJsfCode"`
}
