// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type ImportResourceRecordsReq struct {

    /* 主机记录 (Optional) */
    HostRecord *string `json:"hostRecord"`

    /* 主机记录值  */
    HostValue string `json:"hostValue"`

    /* 解析类型，目前支持类型 A AAAA CNAME TXT CAA SRV MX PTR  */
    RecordType string `json:"recordType"`

    /* TTL值 (Optional) */
    Ttl *int `json:"ttl"`

    /* 优先级，只存在于MX, SRV解析记录类型 (Optional) */
    Priority *int `json:"priority"`

    /* 端口，只存在于SRV解析记录类型 (Optional) */
    Port *int `json:"port"`

    /* 解析记录的权重 (Optional) */
    Weight *int `json:"weight"`
}
