// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type DeviceVO struct {

    /* 设备ID (Optional) */
    DeviceId string `json:"deviceId"`

    /* 设备名称 (Optional) */
    DeviceName string `json:"deviceName"`

    /* 父级设备Id (Optional) */
    ParentId string `json:"parentId"`

    /* 设备类型，同产品类型，0-普通设备，1-网关，2-Edge (Optional) */
    DeviceType string `json:"deviceType"`

    /* 设备状态，0-未激活，1-激活离线，2-激活在线 (Optional) */
    Status int `json:"status"`

    /* 设备标识符 (Optional) */
    Identifier string `json:"identifier"`

    /* 设备秘钥 (Optional) */
    Secret string `json:"secret"`

    /* 设备描述 (Optional) */
    Description string `json:"description"`

    /* 激活时间 (Optional) */
    ActivatedTime int64 `json:"activatedTime"`

    /* 最后连接时间 (Optional) */
    LastConnectedTime int64 `json:"lastConnectedTime"`

    /* 注册时间 (Optional) */
    CreatedTime int64 `json:"createdTime"`

    /* 修改时间 (Optional) */
    UpdatedTime int64 `json:"updatedTime"`

    /* 产品Key (Optional) */
    ProductKey string `json:"productKey"`

    /* 产品名称 (Optional) */
    ProductName string `json:"productName"`

    /* 产品秘钥 (Optional) */
    ProductSecret string `json:"productSecret"`

    /* 设备型号 (Optional) */
    Model string `json:"model"`

    /* 设备厂商 (Optional) */
    Manufacturer string `json:"manufacturer"`

    /* 是否开启动态注册,0:关闭,1:开启，开启动态注册的设备认证类型为一型一密，否则为一机一密 (Optional) */
    DynamicRegister int `json:"dynamicRegister"`
}
