// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type CreateAppRequest struct {

    core.JDCloudRequest

    /* 应用英文名称，由小写字母、数字和中划线组成，以小写字母或数字开头结尾，长度为2-27个字符  */
    AppKey string `json:"appKey"`

    /* 应用中文名称，为空默认和应用英文名称保持一致 (Optional) */
    AppName *string `json:"appName"`

    /* 绑定系统ID  */
    SystemId string `json:"systemId"`

    /* 应用描述，长度不超过100 (Optional) */
    Description *string `json:"description"`

    /* 应用级别：0-核心应用，3-其他应用  */
    AppLevel int `json:"appLevel"`

    /* 应用类型：true-有状态应用，false-无状态应用  */
    Stateful bool `json:"stateful"`

    /* 编程语言：Java、Php、Other  */
    Language string `json:"language"`
}

/*
 * param appKey: 应用英文名称，由小写字母、数字和中划线组成，以小写字母或数字开头结尾，长度为2-27个字符 (Required)
 * param systemId: 绑定系统ID (Required)
 * param appLevel: 应用级别：0-核心应用，3-其他应用 (Required)
 * param stateful: 应用类型：true-有状态应用，false-无状态应用 (Required)
 * param language: 编程语言：Java、Php、Other (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewCreateAppRequest(
    appKey string,
    systemId string,
    appLevel int,
    stateful bool,
    language string,
) *CreateAppRequest {

	return &CreateAppRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/app",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        AppKey: appKey,
        SystemId: systemId,
        AppLevel: appLevel,
        Stateful: stateful,
        Language: language,
	}
}

/*
 * param appKey: 应用英文名称，由小写字母、数字和中划线组成，以小写字母或数字开头结尾，长度为2-27个字符 (Required)
 * param appName: 应用中文名称，为空默认和应用英文名称保持一致 (Optional)
 * param systemId: 绑定系统ID (Required)
 * param description: 应用描述，长度不超过100 (Optional)
 * param appLevel: 应用级别：0-核心应用，3-其他应用 (Required)
 * param stateful: 应用类型：true-有状态应用，false-无状态应用 (Required)
 * param language: 编程语言：Java、Php、Other (Required)
 */
func NewCreateAppRequestWithAllParams(
    appKey string,
    appName *string,
    systemId string,
    description *string,
    appLevel int,
    stateful bool,
    language string,
) *CreateAppRequest {

    return &CreateAppRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/app",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        AppKey: appKey,
        AppName: appName,
        SystemId: systemId,
        Description: description,
        AppLevel: appLevel,
        Stateful: stateful,
        Language: language,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewCreateAppRequestWithoutParam() *CreateAppRequest {

    return &CreateAppRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/app",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param appKey: 应用英文名称，由小写字母、数字和中划线组成，以小写字母或数字开头结尾，长度为2-27个字符(Required) */
func (r *CreateAppRequest) SetAppKey(appKey string) {
    r.AppKey = appKey
}
/* param appName: 应用中文名称，为空默认和应用英文名称保持一致(Optional) */
func (r *CreateAppRequest) SetAppName(appName string) {
    r.AppName = &appName
}
/* param systemId: 绑定系统ID(Required) */
func (r *CreateAppRequest) SetSystemId(systemId string) {
    r.SystemId = systemId
}
/* param description: 应用描述，长度不超过100(Optional) */
func (r *CreateAppRequest) SetDescription(description string) {
    r.Description = &description
}
/* param appLevel: 应用级别：0-核心应用，3-其他应用(Required) */
func (r *CreateAppRequest) SetAppLevel(appLevel int) {
    r.AppLevel = appLevel
}
/* param stateful: 应用类型：true-有状态应用，false-无状态应用(Required) */
func (r *CreateAppRequest) SetStateful(stateful bool) {
    r.Stateful = stateful
}
/* param language: 编程语言：Java、Php、Other(Required) */
func (r *CreateAppRequest) SetLanguage(language string) {
    r.Language = language
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r CreateAppRequest) GetRegionId() string {
    return ""
}

type CreateAppResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result CreateAppResult `json:"result"`
}

type CreateAppResult struct {
    AppId string `json:"appId"`
}