// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type UpgradeInstanceRequest struct {

    core.JDCloudRequest

    /* 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)  */
    RegionId string `json:"regionId"`

    /* RDS 实例ID，唯一标识一个RDS实例  */
    InstanceId string `json:"instanceId"`

    /* 升级操作生效时间，取值为immediate和MaintainTime，默认值为immediate；immediate表示立即生效，MaintainTime表示在运维时间窗口内生效；**备注：MaintainTime暂不支持 (Optional) */
    UpgradeTime *string `json:"upgradeTime"`
}

/*
 * param regionId: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md) (Required)
 * param instanceId: RDS 实例ID，唯一标识一个RDS实例 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewUpgradeInstanceRequest(
    regionId string,
    instanceId string,
) *UpgradeInstanceRequest {

	return &UpgradeInstanceRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/instances/{instanceId}/upgradeInstance",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        InstanceId: instanceId,
	}
}

/*
 * param regionId: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md) (Required)
 * param instanceId: RDS 实例ID，唯一标识一个RDS实例 (Required)
 * param upgradeTime: 升级操作生效时间，取值为immediate和MaintainTime，默认值为immediate；immediate表示立即生效，MaintainTime表示在运维时间窗口内生效；**备注：MaintainTime暂不支持 (Optional)
 */
func NewUpgradeInstanceRequestWithAllParams(
    regionId string,
    instanceId string,
    upgradeTime *string,
) *UpgradeInstanceRequest {

    return &UpgradeInstanceRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/instances/{instanceId}/upgradeInstance",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        InstanceId: instanceId,
        UpgradeTime: upgradeTime,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewUpgradeInstanceRequestWithoutParam() *UpgradeInstanceRequest {

    return &UpgradeInstanceRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/instances/{instanceId}/upgradeInstance",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)(Required) */
func (r *UpgradeInstanceRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}

/* param instanceId: RDS 实例ID，唯一标识一个RDS实例(Required) */
func (r *UpgradeInstanceRequest) SetInstanceId(instanceId string) {
    r.InstanceId = instanceId
}

/* param upgradeTime: 升级操作生效时间，取值为immediate和MaintainTime，默认值为immediate；immediate表示立即生效，MaintainTime表示在运维时间窗口内生效；**备注：MaintainTime暂不支持(Optional) */
func (r *UpgradeInstanceRequest) SetUpgradeTime(upgradeTime string) {
    r.UpgradeTime = &upgradeTime
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r UpgradeInstanceRequest) GetRegionId() string {
    return r.RegionId
}

type UpgradeInstanceResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result UpgradeInstanceResult `json:"result"`
}

type UpgradeInstanceResult struct {
}