// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    hpc "github.com/jdcloud-api/jdcloud-sdk-go/services/hpc/models"
)

type DescribePackagesRequest struct {

    core.JDCloudRequest

    /* 地域ID。
  */
    RegionId string `json:"regionId"`

    /* 按照安装包名称模糊查询。 (Optional) */
    PackageName *string `json:"packageName"`

    /* 按照安装包ID进行筛选。 (Optional) */
    PackageIds []string `json:"packageIds"`

    /* 按照操作系统类型筛选，如ubuntu、openEuler等。 (Optional) */
    OsType *string `json:"osType"`

    /* 按照使用的架构筛选，支持：x86_64,arm64。 (Optional) */
    Architecture *string `json:"architecture"`

    /* 页码；默认为1。 (Optional) */
    PageNumber *int `json:"pageNumber"`

    /* 分页大小；<br>默认为20；取值范围[10, 100]。 (Optional) */
    PageSize *int `json:"pageSize"`
}

/*
 * param regionId: 地域ID。
 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDescribePackagesRequest(
    regionId string,
) *DescribePackagesRequest {

	return &DescribePackagesRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/packages",
			Method:  "GET",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
	}
}

/*
 * param regionId: 地域ID。
 (Required)
 * param packageName: 按照安装包名称模糊查询。 (Optional)
 * param packageIds: 按照安装包ID进行筛选。 (Optional)
 * param osType: 按照操作系统类型筛选，如ubuntu、openEuler等。 (Optional)
 * param architecture: 按照使用的架构筛选，支持：x86_64,arm64。 (Optional)
 * param pageNumber: 页码；默认为1。 (Optional)
 * param pageSize: 分页大小；<br>默认为20；取值范围[10, 100]。 (Optional)
 */
func NewDescribePackagesRequestWithAllParams(
    regionId string,
    packageName *string,
    packageIds []string,
    osType *string,
    architecture *string,
    pageNumber *int,
    pageSize *int,
) *DescribePackagesRequest {

    return &DescribePackagesRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/packages",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        PackageName: packageName,
        PackageIds: packageIds,
        OsType: osType,
        Architecture: architecture,
        PageNumber: pageNumber,
        PageSize: pageSize,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDescribePackagesRequestWithoutParam() *DescribePackagesRequest {

    return &DescribePackagesRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/packages",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID。
(Required) */
func (r *DescribePackagesRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param packageName: 按照安装包名称模糊查询。(Optional) */
func (r *DescribePackagesRequest) SetPackageName(packageName string) {
    r.PackageName = &packageName
}
/* param packageIds: 按照安装包ID进行筛选。(Optional) */
func (r *DescribePackagesRequest) SetPackageIds(packageIds []string) {
    r.PackageIds = packageIds
}
/* param osType: 按照操作系统类型筛选，如ubuntu、openEuler等。(Optional) */
func (r *DescribePackagesRequest) SetOsType(osType string) {
    r.OsType = &osType
}
/* param architecture: 按照使用的架构筛选，支持：x86_64,arm64。(Optional) */
func (r *DescribePackagesRequest) SetArchitecture(architecture string) {
    r.Architecture = &architecture
}
/* param pageNumber: 页码；默认为1。(Optional) */
func (r *DescribePackagesRequest) SetPageNumber(pageNumber int) {
    r.PageNumber = &pageNumber
}
/* param pageSize: 分页大小；<br>默认为20；取值范围[10, 100]。(Optional) */
func (r *DescribePackagesRequest) SetPageSize(pageSize int) {
    r.PageSize = &pageSize
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DescribePackagesRequest) GetRegionId() string {
    return r.RegionId
}

type DescribePackagesResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DescribePackagesResult `json:"result"`
}

type DescribePackagesResult struct {
    PackageList []hpc.PackageInfo `json:"packageList"`
    TotalCount int `json:"totalCount"`
}