// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    smartdba "github.com/jdcloud-api/jdcloud-sdk-go/services/smartdba/models"
)

type DescribeDiagnoseRequest struct {

    core.JDCloudRequest

    /* 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)  */
    RegionId string `json:"regionId"`

    /* RDS 实例ID，唯一标识一个RDS实例  */
    InstanceGid string `json:"instanceGid"`

    /* 诊断任务id  */
    DiagnoseId string `json:"diagnoseId"`
}

/*
 * param regionId: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md) (Required)
 * param instanceGid: RDS 实例ID，唯一标识一个RDS实例 (Required)
 * param diagnoseId: 诊断任务id (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDescribeDiagnoseRequest(
    regionId string,
    instanceGid string,
    diagnoseId string,
) *DescribeDiagnoseRequest {

	return &DescribeDiagnoseRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/instance/{instanceGid}/diagnoses/{diagnoseId}",
			Method:  "GET",
			Header:  nil,
			Version: "v2",
		},
        RegionId: regionId,
        InstanceGid: instanceGid,
        DiagnoseId: diagnoseId,
	}
}

/*
 * param regionId: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md) (Required)
 * param instanceGid: RDS 实例ID，唯一标识一个RDS实例 (Required)
 * param diagnoseId: 诊断任务id (Required)
 */
func NewDescribeDiagnoseRequestWithAllParams(
    regionId string,
    instanceGid string,
    diagnoseId string,
) *DescribeDiagnoseRequest {

    return &DescribeDiagnoseRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/instance/{instanceGid}/diagnoses/{diagnoseId}",
            Method:  "GET",
            Header:  nil,
            Version: "v2",
        },
        RegionId: regionId,
        InstanceGid: instanceGid,
        DiagnoseId: diagnoseId,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDescribeDiagnoseRequestWithoutParam() *DescribeDiagnoseRequest {

    return &DescribeDiagnoseRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/instance/{instanceGid}/diagnoses/{diagnoseId}",
            Method:  "GET",
            Header:  nil,
            Version: "v2",
        },
    }
}

/* param regionId: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)(Required) */
func (r *DescribeDiagnoseRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}

/* param instanceGid: RDS 实例ID，唯一标识一个RDS实例(Required) */
func (r *DescribeDiagnoseRequest) SetInstanceGid(instanceGid string) {
    r.InstanceGid = instanceGid
}

/* param diagnoseId: 诊断任务id(Required) */
func (r *DescribeDiagnoseRequest) SetDiagnoseId(diagnoseId string) {
    r.DiagnoseId = diagnoseId
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DescribeDiagnoseRequest) GetRegionId() string {
    return r.RegionId
}

type DescribeDiagnoseResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DescribeDiagnoseResult `json:"result"`
}

type DescribeDiagnoseResult struct {
    Status string `json:"status"`
    Data smartdba.DiagnoseDetail `json:"data"`
}