// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type InstanceStatisticsInfoVo struct {

    /* 总实例数 (Optional) */
    TotalInstances int `json:"totalInstances"`

    /* 成功实例数 (Optional) */
    SuccessInstances int `json:"successInstances"`

    /* 失败实例数 (Optional) */
    FailedInstances int `json:"failedInstances"`

    /* 未就绪实例数 (Optional) */
    PendingInstances int `json:"pendingInstances"`

    /* 等待实例数 (Optional) */
    AwaitingInstances string `json:"awaitingInstances"`

    /* 被终止实例数 (Optional) */
    KilledInstances int `json:"killedInstances"`

    /* 运行中实例数 (Optional) */
    RunningInstances int `json:"runningInstances"`
}
