// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type TaskDebugHistoryListReq struct {

    /* 任务的草稿id (Optional) */
    TaskDraftId string `json:"taskDraftId"`

    /* 分页的每页的记录数 (Optional) */
    PageSize int `json:"pageSize"`

    /* 第几页 (Optional) */
    PageNum int `json:"pageNum"`

    /* 开始时间起点 (Optional) */
    StartTimeFrom string `json:"startTimeFrom"`

    /* 开始时间终点 (Optional) */
    StartTimeEnd string `json:"startTimeEnd"`

    /* 结束时间起点 (Optional) */
    EndTimeFrom string `json:"endTimeFrom"`

    /* 结束时间终点 (Optional) */
    EndTimeEnd string `json:"endTimeEnd"`

    /* 任务的状态列表, CANCELLING 终止、WAITING_EXEC 等待执行、RUNNING 执行中、SUCCESS 执行成功、FAILURE 执行失败、CANCELLED 终止执行、TIMEOUT 执行超时 (Optional) */
    Statuses []string `json:"statuses"`
}
