// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type TaskHistoryVersionInfoRes struct {

    /* 历史记录 ID (Optional) */
    HistoryId int64 `json:"historyId"`

    /* 排序 ID (Optional) */
    SortId int `json:"sortId"`

    /* 版本号 (Optional) */
    Version int `json:"version"`

    /* 原因 (Optional) */
    Reason string `json:"reason"`

    /* 提交时间 (Optional) */
    CommitTime string `json:"commitTime"`

    /* 提交人 (Optional) */
    Committer string `json:"committer"`

    /* 任务草稿 ID (Optional) */
    TaskDraftId string `json:"taskDraftId"`

    /* 任务 ID (Optional) */
    TaskId string `json:"taskId"`

    /* 任务名称 (Optional) */
    TaskName string `json:"taskName"`

    /* 任务类型 (Optional) */
    TaskType string `json:"taskType"`

    /* 状态 (Optional) */
    Status string `json:"status"`

    /* 描述 (Optional) */
    Desc string `json:"desc"`
}
