// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type TaskDetailVo struct {

    /* 基础信息
任务ID (Optional) */
    Id string `json:"id"`

    /* 任务名称 (Optional) */
    Name string `json:"name"`

    /* 任务描述 (Optional) */
    Description string `json:"description"`

    /* 任务类型 (Optional) */
    TaskType string `json:"taskType"`

    /* 任务类型-中文 (Optional) */
    TaskTypeLabel string `json:"taskTypeLabel"`

    /* 负责人列表 (Optional) */
    Owners []UserInfoVo `json:"owners"`

    /* 协作人列表 (Optional) */
    Collaborators []UserInfoVo `json:"collaborators"`

    /* 创建时间 (Optional) */
    CreateTimestamp int64 `json:"createTimestamp"`

    /* 更新时间 (Optional) */
    UpdateTimestamp int64 `json:"updateTimestamp"`

    /* 任务失效时间 (Optional) */
    ExpireTimestamp int64 `json:"expireTimestamp"`

    /* 调度信息
优先级 (Optional) */
    Priority int `json:"priority"`

    /* 优先级-中文 (Optional) */
    PriorityLabel string `json:"priorityLabel"`

    /* 周期 (Optional) */
    Cycle string `json:"cycle"`

    /* 周期-中文 (Optional) */
    CycleLabel string `json:"cycleLabel"`

    /* CRON表达式 (Optional) */
    CronExpression string `json:"cronExpression"`

    /* 延迟执行时间（单位：分钟） (Optional) */
    Delay int `json:"delay"`

    /* 超时时间（单位：分钟） (Optional) */
    Timeout int `json:"timeout"`

    /* 失败重试次数 (Optional) */
    RetryTimes int `json:"retryTimes"`

    /* 失败重试间隔（单位：分钟） (Optional) */
    RetryInterval int `json:"retryInterval"`

    /* 预警信息
预警方式 (Optional) */
    AlarmMethods []AlarmMethodVo `json:"alarmMethods"`

    /* 预警时机 (Optional) */
    AlarmTimings []AlarmTimingVo `json:"alarmTimings"`

    /* 预警接收人 (Optional) */
    AlarmReceivers []UserInfoVo `json:"alarmReceivers"`

    /* 延迟启动告警时间 (Optional) */
    StartDelayAlarmTime string `json:"startDelayAlarmTime"`

    /* 延迟结束告警时间 (Optional) */
    FinishDelayAlarmTime string `json:"finishDelayAlarmTime"`

    /* 内部任务的任务ID列表（仅工作流任务有该属性） (Optional) */
    InternalTaskIds []string `json:"internalTaskIds"`

    /* 所属工作空间编码 (Optional) */
    WorkspaceCode string `json:"workspaceCode"`

    /* 所属工作空间名称 (Optional) */
    WorkspaceName string `json:"workspaceName"`
}
