// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    aifactory "github.com/jdcloud-api/jdcloud-sdk-go/services/aifactory/models"
)

type DataWorkshopCreateOrUpdateClusterRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /* 集群ID - 更新时必传 (Optional) */
    Id *string `json:"id"`

    /* 集群实例名称 (Optional) */
    Name *string `json:"name"`

    /* 所属队列ID (Optional) */
    QueueId *string `json:"queueId"`

    /* 集群类型: analyze-SQL查询、inference-推理、custom-自定义 (Optional) */
    ClusterType *string `json:"clusterType"`

    /* 镜像配置 (Optional) */
    ImageConfig *aifactory.ResidentImageConfig `json:"imageConfig"`

    /* 环境变量 (Optional) */
    EnvConfigs []aifactory.EnvConfig `json:"envConfigs"`

    /* 存储挂载配置 (Optional) */
    StorageMountConfigs []aifactory.ResidentStorageMountConfig `json:"storageMountConfigs"`

    /* 属性配置 - 仅inference类型支持 (Optional) */
    PropertyConfigs []aifactory.PairConfig `json:"propertyConfigs"`

    /* 模型路径 - 仅inference类型支持 (Optional) */
    ModelPath *string `json:"modelPath"`

    /* 推理框架 - 仅inference类型支持：vllm-VLLM (Optional) */
    InferenceFrameWork *string `json:"inferenceFrameWork"`

    /* 启动命令 - 仅inference类型支持 (Optional) */
    BootCommand *string `json:"bootCommand"`

    /* 集群配置 (Optional) */
    ClusterConfig *aifactory.RayConfig `json:"clusterConfig"`

    /*  (Optional) */
    AlertConfig *aifactory.AlertConfig `json:"alertConfig"`

    /* 标签 (Optional) */
    Tags []aifactory.PairConfig `json:"tags"`

    /* 负责人列表 (Optional) */
    Owners []string `json:"owners"`

    /* 是否开启队列内抢占 (Optional) */
    EnablePrompt *bool `json:"enablePrompt"`

    /* 抢占优先级：HIGH、MEDIUM、LOW (Optional) */
    PodPriority *string `json:"podPriority"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDataWorkshopCreateOrUpdateClusterRequest(
    regionId string,
    appName string,
) *DataWorkshopCreateOrUpdateClusterRequest {

	return &DataWorkshopCreateOrUpdateClusterRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/dataWorkshopCreateOrUpdateCluster",
			Method:  "POST",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        AppName: appName,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param id: 集群ID - 更新时必传 (Optional)
 * param name: 集群实例名称 (Optional)
 * param queueId: 所属队列ID (Optional)
 * param clusterType: 集群类型: analyze-SQL查询、inference-推理、custom-自定义 (Optional)
 * param imageConfig: 镜像配置 (Optional)
 * param envConfigs: 环境变量 (Optional)
 * param storageMountConfigs: 存储挂载配置 (Optional)
 * param propertyConfigs: 属性配置 - 仅inference类型支持 (Optional)
 * param modelPath: 模型路径 - 仅inference类型支持 (Optional)
 * param inferenceFrameWork: 推理框架 - 仅inference类型支持：vllm-VLLM (Optional)
 * param bootCommand: 启动命令 - 仅inference类型支持 (Optional)
 * param clusterConfig: 集群配置 (Optional)
 * param alertConfig:  (Optional)
 * param tags: 标签 (Optional)
 * param owners: 负责人列表 (Optional)
 * param enablePrompt: 是否开启队列内抢占 (Optional)
 * param podPriority: 抢占优先级：HIGH、MEDIUM、LOW (Optional)
 */
func NewDataWorkshopCreateOrUpdateClusterRequestWithAllParams(
    regionId string,
    appName string,
    id *string,
    name *string,
    queueId *string,
    clusterType *string,
    imageConfig *aifactory.ResidentImageConfig,
    envConfigs []aifactory.EnvConfig,
    storageMountConfigs []aifactory.ResidentStorageMountConfig,
    propertyConfigs []aifactory.PairConfig,
    modelPath *string,
    inferenceFrameWork *string,
    bootCommand *string,
    clusterConfig *aifactory.RayConfig,
    alertConfig *aifactory.AlertConfig,
    tags []aifactory.PairConfig,
    owners []string,
    enablePrompt *bool,
    podPriority *string,
) *DataWorkshopCreateOrUpdateClusterRequest {

    return &DataWorkshopCreateOrUpdateClusterRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/dataWorkshopCreateOrUpdateCluster",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        AppName: appName,
        Id: id,
        Name: name,
        QueueId: queueId,
        ClusterType: clusterType,
        ImageConfig: imageConfig,
        EnvConfigs: envConfigs,
        StorageMountConfigs: storageMountConfigs,
        PropertyConfigs: propertyConfigs,
        ModelPath: modelPath,
        InferenceFrameWork: inferenceFrameWork,
        BootCommand: bootCommand,
        ClusterConfig: clusterConfig,
        AlertConfig: alertConfig,
        Tags: tags,
        Owners: owners,
        EnablePrompt: enablePrompt,
        PodPriority: podPriority,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDataWorkshopCreateOrUpdateClusterRequestWithoutParam() *DataWorkshopCreateOrUpdateClusterRequest {

    return &DataWorkshopCreateOrUpdateClusterRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/dataWorkshopCreateOrUpdateCluster",
            Method:  "POST",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param id: 集群ID - 更新时必传(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetId(id string) {
    r.Id = &id
}
/* param name: 集群实例名称(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetName(name string) {
    r.Name = &name
}
/* param queueId: 所属队列ID(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetQueueId(queueId string) {
    r.QueueId = &queueId
}
/* param clusterType: 集群类型: analyze-SQL查询、inference-推理、custom-自定义(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetClusterType(clusterType string) {
    r.ClusterType = &clusterType
}
/* param imageConfig: 镜像配置(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetImageConfig(imageConfig *aifactory.ResidentImageConfig) {
    r.ImageConfig = imageConfig
}
/* param envConfigs: 环境变量(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetEnvConfigs(envConfigs []aifactory.EnvConfig) {
    r.EnvConfigs = envConfigs
}
/* param storageMountConfigs: 存储挂载配置(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetStorageMountConfigs(storageMountConfigs []aifactory.ResidentStorageMountConfig) {
    r.StorageMountConfigs = storageMountConfigs
}
/* param propertyConfigs: 属性配置 - 仅inference类型支持(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetPropertyConfigs(propertyConfigs []aifactory.PairConfig) {
    r.PropertyConfigs = propertyConfigs
}
/* param modelPath: 模型路径 - 仅inference类型支持(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetModelPath(modelPath string) {
    r.ModelPath = &modelPath
}
/* param inferenceFrameWork: 推理框架 - 仅inference类型支持：vllm-VLLM(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetInferenceFrameWork(inferenceFrameWork string) {
    r.InferenceFrameWork = &inferenceFrameWork
}
/* param bootCommand: 启动命令 - 仅inference类型支持(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetBootCommand(bootCommand string) {
    r.BootCommand = &bootCommand
}
/* param clusterConfig: 集群配置(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetClusterConfig(clusterConfig *aifactory.RayConfig) {
    r.ClusterConfig = clusterConfig
}
/* param alertConfig: (Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetAlertConfig(alertConfig *aifactory.AlertConfig) {
    r.AlertConfig = alertConfig
}
/* param tags: 标签(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetTags(tags []aifactory.PairConfig) {
    r.Tags = tags
}
/* param owners: 负责人列表(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetOwners(owners []string) {
    r.Owners = owners
}
/* param enablePrompt: 是否开启队列内抢占(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetEnablePrompt(enablePrompt bool) {
    r.EnablePrompt = &enablePrompt
}
/* param podPriority: 抢占优先级：HIGH、MEDIUM、LOW(Optional) */
func (r *DataWorkshopCreateOrUpdateClusterRequest) SetPodPriority(podPriority string) {
    r.PodPriority = &podPriority
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DataWorkshopCreateOrUpdateClusterRequest) GetRegionId() string {
    return r.RegionId
}

type DataWorkshopCreateOrUpdateClusterResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DataWorkshopCreateOrUpdateClusterResult `json:"result"`
}

type DataWorkshopCreateOrUpdateClusterResult struct {
    Code string `json:"code"`
    Message string `json:"message"`
    Result string `json:"result"`
}