// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/lshuining/jdcloud-sdk-go/core"
)

type DeleteBackupSynchronicitiesRequest struct {

    core.JDCloudRequest

    /* Region ID  */
    RegionId string `json:"regionId"`

    /* service ID  */
    ServiceId string `json:"serviceId"`
}

/*
 * param regionId: Region ID (Required)
 * param serviceId: service ID (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewDeleteBackupSynchronicitiesRequest(
    regionId string,
    serviceId string,
) *DeleteBackupSynchronicitiesRequest {

	return &DeleteBackupSynchronicitiesRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/backupSynchronicities/{serviceId}",
			Method:  "DELETE",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        ServiceId: serviceId,
	}
}

/*
 * param regionId: Region ID (Required)
 * param serviceId: service ID (Required)
 */
func NewDeleteBackupSynchronicitiesRequestWithAllParams(
    regionId string,
    serviceId string,
) *DeleteBackupSynchronicitiesRequest {

    return &DeleteBackupSynchronicitiesRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/backupSynchronicities/{serviceId}",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        ServiceId: serviceId,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewDeleteBackupSynchronicitiesRequestWithoutParam() *DeleteBackupSynchronicitiesRequest {

    return &DeleteBackupSynchronicitiesRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/backupSynchronicities/{serviceId}",
            Method:  "DELETE",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: Region ID(Required) */
func (r *DeleteBackupSynchronicitiesRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}

/* param serviceId: service ID(Required) */
func (r *DeleteBackupSynchronicitiesRequest) SetServiceId(serviceId string) {
    r.ServiceId = serviceId
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r DeleteBackupSynchronicitiesRequest) GetRegionId() string {
    return r.RegionId
}

type DeleteBackupSynchronicitiesResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result DeleteBackupSynchronicitiesResult `json:"result"`
}

type DeleteBackupSynchronicitiesResult struct {
    ServiceId string `json:"serviceId"`
}