// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type UnbindInstanceRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /* 引擎 Code  */
    EngineCode string `json:"engineCode"`

    /* 实例 Code  */
    InstanceCode string `json:"instanceCode"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param engineCode: 引擎 Code (Required)
 * param instanceCode: 实例 Code (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewUnbindInstanceRequest(
    regionId string,
    appName string,
    engineCode string,
    instanceCode string,
) *UnbindInstanceRequest {

	return &UnbindInstanceRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/unbindInstance",
			Method:  "POST",
			Header:  nil,
			Version: "v2",
		},
        RegionId: regionId,
        AppName: appName,
        EngineCode: engineCode,
        InstanceCode: instanceCode,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param engineCode: 引擎 Code (Required)
 * param instanceCode: 实例 Code (Required)
 */
func NewUnbindInstanceRequestWithAllParams(
    regionId string,
    appName string,
    engineCode string,
    instanceCode string,
) *UnbindInstanceRequest {

    return &UnbindInstanceRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/unbindInstance",
            Method:  "POST",
            Header:  nil,
            Version: "v2",
        },
        RegionId: regionId,
        AppName: appName,
        EngineCode: engineCode,
        InstanceCode: instanceCode,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewUnbindInstanceRequestWithoutParam() *UnbindInstanceRequest {

    return &UnbindInstanceRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/unbindInstance",
            Method:  "POST",
            Header:  nil,
            Version: "v2",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *UnbindInstanceRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *UnbindInstanceRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param engineCode: 引擎 Code(Required) */
func (r *UnbindInstanceRequest) SetEngineCode(engineCode string) {
    r.EngineCode = engineCode
}
/* param instanceCode: 实例 Code(Required) */
func (r *UnbindInstanceRequest) SetInstanceCode(instanceCode string) {
    r.InstanceCode = instanceCode
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r UnbindInstanceRequest) GetRegionId() string {
    return r.RegionId
}

type UnbindInstanceResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result UnbindInstanceResult `json:"result"`
}

type UnbindInstanceResult struct {
    Code string `json:"code"`
    Message string `json:"message"`
}