// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
    shenhaiplatform "github.com/jdcloud-api/jdcloud-sdk-go/services/shenhaiplatform/models"
)

type UranusFlowSearchNodeRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /* 工作流草稿id (Optional) */
    FlowDraftId *string `json:"flowDraftId"`

    /* 分页的每页的记录数 (Optional) */
    PageSize *int `json:"pageSize"`

    /* 第几页 (Optional) */
    PageNum *int `json:"pageNum"`

    /* 任务创建时间起点 (Optional) */
    CreateTimeFrom *string `json:"createTimeFrom"`

    /* 任务创建时间终点 (Optional) */
    CreateTimeEnd *string `json:"createTimeEnd"`

    /* 任务更新时间起点 (Optional) */
    UpdateTimeFrom *string `json:"updateTimeFrom"`

    /* 任务更新时间终点 (Optional) */
    UpdateTimeEnd *string `json:"updateTimeEnd"`

    /* 任务负责人 (Optional) */
    Manager *string `json:"manager"`

    /* 任务名称 (Optional) */
    TaskName *string `json:"taskName"`

    /* 任务类型, JCW_SQL jcw引擎的SQL任务、PYTHON python任务、SHELL Linux脚本任务、SPARK_JAR sparkJar任务、STAR_ROCKS starrocks任务、MYSQL mysql任务、LOOP 循环节点任务、PIPE 数据集成任务 (Optional) */
    TaskType []string `json:"taskType"`

    /* 任务的种类, INTEGRATION 数据集成、JCW jcw引擎、DATA_SOURCE 数据源类型、COMMON 通用类型 (Optional) */
    TaskClassify *string `json:"taskClassify"`

    /* 任务的提交到运维中心的状态, UNPUBLISH 未提交、PUBLISHED 已提交、UPDATE_UNPUBLISH 更新未提交 (Optional) */
    TaskStatus *string `json:"taskStatus"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewUranusFlowSearchNodeRequest(
    regionId string,
    appName string,
) *UranusFlowSearchNodeRequest {

	return &UranusFlowSearchNodeRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/uranusFlowSearchNode",
			Method:  "POST",
			Header:  nil,
			Version: "v2",
		},
        RegionId: regionId,
        AppName: appName,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param flowDraftId: 工作流草稿id (Optional)
 * param pageSize: 分页的每页的记录数 (Optional)
 * param pageNum: 第几页 (Optional)
 * param createTimeFrom: 任务创建时间起点 (Optional)
 * param createTimeEnd: 任务创建时间终点 (Optional)
 * param updateTimeFrom: 任务更新时间起点 (Optional)
 * param updateTimeEnd: 任务更新时间终点 (Optional)
 * param manager: 任务负责人 (Optional)
 * param taskName: 任务名称 (Optional)
 * param taskType: 任务类型, JCW_SQL jcw引擎的SQL任务、PYTHON python任务、SHELL Linux脚本任务、SPARK_JAR sparkJar任务、STAR_ROCKS starrocks任务、MYSQL mysql任务、LOOP 循环节点任务、PIPE 数据集成任务 (Optional)
 * param taskClassify: 任务的种类, INTEGRATION 数据集成、JCW jcw引擎、DATA_SOURCE 数据源类型、COMMON 通用类型 (Optional)
 * param taskStatus: 任务的提交到运维中心的状态, UNPUBLISH 未提交、PUBLISHED 已提交、UPDATE_UNPUBLISH 更新未提交 (Optional)
 */
func NewUranusFlowSearchNodeRequestWithAllParams(
    regionId string,
    appName string,
    flowDraftId *string,
    pageSize *int,
    pageNum *int,
    createTimeFrom *string,
    createTimeEnd *string,
    updateTimeFrom *string,
    updateTimeEnd *string,
    manager *string,
    taskName *string,
    taskType []string,
    taskClassify *string,
    taskStatus *string,
) *UranusFlowSearchNodeRequest {

    return &UranusFlowSearchNodeRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/uranusFlowSearchNode",
            Method:  "POST",
            Header:  nil,
            Version: "v2",
        },
        RegionId: regionId,
        AppName: appName,
        FlowDraftId: flowDraftId,
        PageSize: pageSize,
        PageNum: pageNum,
        CreateTimeFrom: createTimeFrom,
        CreateTimeEnd: createTimeEnd,
        UpdateTimeFrom: updateTimeFrom,
        UpdateTimeEnd: updateTimeEnd,
        Manager: manager,
        TaskName: taskName,
        TaskType: taskType,
        TaskClassify: taskClassify,
        TaskStatus: taskStatus,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewUranusFlowSearchNodeRequestWithoutParam() *UranusFlowSearchNodeRequest {

    return &UranusFlowSearchNodeRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/uranusFlowSearchNode",
            Method:  "POST",
            Header:  nil,
            Version: "v2",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *UranusFlowSearchNodeRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *UranusFlowSearchNodeRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param flowDraftId: 工作流草稿id(Optional) */
func (r *UranusFlowSearchNodeRequest) SetFlowDraftId(flowDraftId string) {
    r.FlowDraftId = &flowDraftId
}
/* param pageSize: 分页的每页的记录数(Optional) */
func (r *UranusFlowSearchNodeRequest) SetPageSize(pageSize int) {
    r.PageSize = &pageSize
}
/* param pageNum: 第几页(Optional) */
func (r *UranusFlowSearchNodeRequest) SetPageNum(pageNum int) {
    r.PageNum = &pageNum
}
/* param createTimeFrom: 任务创建时间起点(Optional) */
func (r *UranusFlowSearchNodeRequest) SetCreateTimeFrom(createTimeFrom string) {
    r.CreateTimeFrom = &createTimeFrom
}
/* param createTimeEnd: 任务创建时间终点(Optional) */
func (r *UranusFlowSearchNodeRequest) SetCreateTimeEnd(createTimeEnd string) {
    r.CreateTimeEnd = &createTimeEnd
}
/* param updateTimeFrom: 任务更新时间起点(Optional) */
func (r *UranusFlowSearchNodeRequest) SetUpdateTimeFrom(updateTimeFrom string) {
    r.UpdateTimeFrom = &updateTimeFrom
}
/* param updateTimeEnd: 任务更新时间终点(Optional) */
func (r *UranusFlowSearchNodeRequest) SetUpdateTimeEnd(updateTimeEnd string) {
    r.UpdateTimeEnd = &updateTimeEnd
}
/* param manager: 任务负责人(Optional) */
func (r *UranusFlowSearchNodeRequest) SetManager(manager string) {
    r.Manager = &manager
}
/* param taskName: 任务名称(Optional) */
func (r *UranusFlowSearchNodeRequest) SetTaskName(taskName string) {
    r.TaskName = &taskName
}
/* param taskType: 任务类型, JCW_SQL jcw引擎的SQL任务、PYTHON python任务、SHELL Linux脚本任务、SPARK_JAR sparkJar任务、STAR_ROCKS starrocks任务、MYSQL mysql任务、LOOP 循环节点任务、PIPE 数据集成任务(Optional) */
func (r *UranusFlowSearchNodeRequest) SetTaskType(taskType []string) {
    r.TaskType = taskType
}
/* param taskClassify: 任务的种类, INTEGRATION 数据集成、JCW jcw引擎、DATA_SOURCE 数据源类型、COMMON 通用类型(Optional) */
func (r *UranusFlowSearchNodeRequest) SetTaskClassify(taskClassify string) {
    r.TaskClassify = &taskClassify
}
/* param taskStatus: 任务的提交到运维中心的状态, UNPUBLISH 未提交、PUBLISHED 已提交、UPDATE_UNPUBLISH 更新未提交(Optional) */
func (r *UranusFlowSearchNodeRequest) SetTaskStatus(taskStatus string) {
    r.TaskStatus = &taskStatus
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r UranusFlowSearchNodeRequest) GetRegionId() string {
    return r.RegionId
}

type UranusFlowSearchNodeResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result UranusFlowSearchNodeResult `json:"result"`
}

type UranusFlowSearchNodeResult struct {
    Code string `json:"code"`
    ErrorTitle string `json:"errorTitle"`
    ErrorMsg string `json:"errorMsg"`
    SubCode string `json:"subCode"`
    Result shenhaiplatform.PageResultTaskCanvasInfoRes `json:"result"`
}