// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type UranusTaskKillRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /* 任务的调试id  */
    DebugId int `json:"debugId"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param debugId: 任务的调试id (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewUranusTaskKillRequest(
    regionId string,
    appName string,
    debugId int,
) *UranusTaskKillRequest {

	return &UranusTaskKillRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/uranusTaskKill",
			Method:  "GET",
			Header:  nil,
			Version: "v2",
		},
        RegionId: regionId,
        AppName: appName,
        DebugId: debugId,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param debugId: 任务的调试id (Required)
 */
func NewUranusTaskKillRequestWithAllParams(
    regionId string,
    appName string,
    debugId int,
) *UranusTaskKillRequest {

    return &UranusTaskKillRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/uranusTaskKill",
            Method:  "GET",
            Header:  nil,
            Version: "v2",
        },
        RegionId: regionId,
        AppName: appName,
        DebugId: debugId,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewUranusTaskKillRequestWithoutParam() *UranusTaskKillRequest {

    return &UranusTaskKillRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/uranusTaskKill",
            Method:  "GET",
            Header:  nil,
            Version: "v2",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *UranusTaskKillRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *UranusTaskKillRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param debugId: 任务的调试id(Required) */
func (r *UranusTaskKillRequest) SetDebugId(debugId int) {
    r.DebugId = debugId
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r UranusTaskKillRequest) GetRegionId() string {
    return r.RegionId
}

type UranusTaskKillResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result UranusTaskKillResult `json:"result"`
}

type UranusTaskKillResult struct {
    Code string `json:"code"`
    ErrorTitle string `json:"errorTitle"`
    ErrorMsg string `json:"errorMsg"`
    SubCode string `json:"subCode"`
    Result bool `json:"result"`
}