// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type WorkspaceBundleOrUnBundleResourceRequest struct {

    core.JDCloudRequest

    /* 地域ID  */
    RegionId string `json:"regionId"`

    /* 应用名称  */
    AppName string `json:"appName"`

    /* 工作空间code (Optional) */
    WorkspaceCode *string `json:"workspaceCode"`

    /*  (Optional) */
    UserPin *string `json:"userPin"`

    /*  (Optional) */
    CalculateResourceCode []string `json:"calculateResourceCode"`

    /*  (Optional) */
    IntegrationResourceCode []string `json:"integrationResourceCode"`

    /*  (Optional) */
    BundleResource *bool `json:"bundleResource"`
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewWorkspaceBundleOrUnBundleResourceRequest(
    regionId string,
    appName string,
) *WorkspaceBundleOrUnBundleResourceRequest {

	return &WorkspaceBundleOrUnBundleResourceRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/apps/{appName}/workspaceBundleOrUnBundleResource",
			Method:  "POST",
			Header:  nil,
			Version: "v2",
		},
        RegionId: regionId,
        AppName: appName,
	}
}

/*
 * param regionId: 地域ID (Required)
 * param appName: 应用名称 (Required)
 * param workspaceCode: 工作空间code (Optional)
 * param userPin:  (Optional)
 * param calculateResourceCode:  (Optional)
 * param integrationResourceCode:  (Optional)
 * param bundleResource:  (Optional)
 */
func NewWorkspaceBundleOrUnBundleResourceRequestWithAllParams(
    regionId string,
    appName string,
    workspaceCode *string,
    userPin *string,
    calculateResourceCode []string,
    integrationResourceCode []string,
    bundleResource *bool,
) *WorkspaceBundleOrUnBundleResourceRequest {

    return &WorkspaceBundleOrUnBundleResourceRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/workspaceBundleOrUnBundleResource",
            Method:  "POST",
            Header:  nil,
            Version: "v2",
        },
        RegionId: regionId,
        AppName: appName,
        WorkspaceCode: workspaceCode,
        UserPin: userPin,
        CalculateResourceCode: calculateResourceCode,
        IntegrationResourceCode: integrationResourceCode,
        BundleResource: bundleResource,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewWorkspaceBundleOrUnBundleResourceRequestWithoutParam() *WorkspaceBundleOrUnBundleResourceRequest {

    return &WorkspaceBundleOrUnBundleResourceRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/apps/{appName}/workspaceBundleOrUnBundleResource",
            Method:  "POST",
            Header:  nil,
            Version: "v2",
        },
    }
}

/* param regionId: 地域ID(Required) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param appName: 应用名称(Required) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetAppName(appName string) {
    r.AppName = appName
}
/* param workspaceCode: 工作空间code(Optional) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetWorkspaceCode(workspaceCode string) {
    r.WorkspaceCode = &workspaceCode
}
/* param userPin: (Optional) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetUserPin(userPin string) {
    r.UserPin = &userPin
}
/* param calculateResourceCode: (Optional) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetCalculateResourceCode(calculateResourceCode []string) {
    r.CalculateResourceCode = calculateResourceCode
}
/* param integrationResourceCode: (Optional) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetIntegrationResourceCode(integrationResourceCode []string) {
    r.IntegrationResourceCode = integrationResourceCode
}
/* param bundleResource: (Optional) */
func (r *WorkspaceBundleOrUnBundleResourceRequest) SetBundleResource(bundleResource bool) {
    r.BundleResource = &bundleResource
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r WorkspaceBundleOrUnBundleResourceRequest) GetRegionId() string {
    return r.RegionId
}

type WorkspaceBundleOrUnBundleResourceResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result WorkspaceBundleOrUnBundleResourceResult `json:"result"`
}

type WorkspaceBundleOrUnBundleResourceResult struct {
}