// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type Department struct {

    /* ID (Optional) */
    Id int `json:"id"`

    /* 部门编号 (Optional) */
    DepId string `json:"depId"`

    /* 部门名称 (Optional) */
    DepName string `json:"depName"`

    /* 是否删除0未删除,1已删除 (Optional) */
    IsDeleted int `json:"isDeleted"`
}
