// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/jdcloud-api/jdcloud-sdk-go/core"
)

type ModifyMaintenanceEventRequest struct {

    core.JDCloudRequest

    /* 地域ID。  */
    RegionId string `json:"regionId"`

    /* 运维事件ID
  */
    EventId string `json:"eventId"`

    /* 预约执行时间，形如2023-01-01 12:00:00
参数条件：
 1. 事件的eventState为Scheduled，预约时间需晚于当前时间至少15分钟，且在deadlineTime前15分钟。与eventState二者只能填入其一。
 2. 当事件类型为实例所在宿主机下线时，该参数为必填项。
 (Optional) */
    EventTime *string `json:"eventTime"`

    /* 运维事件状态，目前仅支持Reject（灰度）
参数条件：
1. eventState为Scheduled，与eventTime二者只能填入其一。
 (Optional) */
    EventState *string `json:"eventState"`
}

/*
 * param regionId: 地域ID。 (Required)
 * param eventId: 运维事件ID
 (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewModifyMaintenanceEventRequest(
    regionId string,
    eventId string,
) *ModifyMaintenanceEventRequest {

	return &ModifyMaintenanceEventRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/regions/{regionId}/maintenanceEvents/{eventId}",
			Method:  "PATCH",
			Header:  nil,
			Version: "v1",
		},
        RegionId: regionId,
        EventId: eventId,
	}
}

/*
 * param regionId: 地域ID。 (Required)
 * param eventId: 运维事件ID
 (Required)
 * param eventTime: 预约执行时间，形如2023-01-01 12:00:00
参数条件：
 1. 事件的eventState为Scheduled，预约时间需晚于当前时间至少15分钟，且在deadlineTime前15分钟。与eventState二者只能填入其一。
 2. 当事件类型为实例所在宿主机下线时，该参数为必填项。
 (Optional)
 * param eventState: 运维事件状态，目前仅支持Reject（灰度）
参数条件：
1. eventState为Scheduled，与eventTime二者只能填入其一。
 (Optional)
 */
func NewModifyMaintenanceEventRequestWithAllParams(
    regionId string,
    eventId string,
    eventTime *string,
    eventState *string,
) *ModifyMaintenanceEventRequest {

    return &ModifyMaintenanceEventRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/maintenanceEvents/{eventId}",
            Method:  "PATCH",
            Header:  nil,
            Version: "v1",
        },
        RegionId: regionId,
        EventId: eventId,
        EventTime: eventTime,
        EventState: eventState,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewModifyMaintenanceEventRequestWithoutParam() *ModifyMaintenanceEventRequest {

    return &ModifyMaintenanceEventRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/regions/{regionId}/maintenanceEvents/{eventId}",
            Method:  "PATCH",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param regionId: 地域ID。(Required) */
func (r *ModifyMaintenanceEventRequest) SetRegionId(regionId string) {
    r.RegionId = regionId
}
/* param eventId: 运维事件ID
(Required) */
func (r *ModifyMaintenanceEventRequest) SetEventId(eventId string) {
    r.EventId = eventId
}
/* param eventTime: 预约执行时间，形如2023-01-01 12:00:00
参数条件：
 1. 事件的eventState为Scheduled，预约时间需晚于当前时间至少15分钟，且在deadlineTime前15分钟。与eventState二者只能填入其一。
 2. 当事件类型为实例所在宿主机下线时，该参数为必填项。
(Optional) */
func (r *ModifyMaintenanceEventRequest) SetEventTime(eventTime string) {
    r.EventTime = &eventTime
}
/* param eventState: 运维事件状态，目前仅支持Reject（灰度）
参数条件：
1. eventState为Scheduled，与eventTime二者只能填入其一。
(Optional) */
func (r *ModifyMaintenanceEventRequest) SetEventState(eventState string) {
    r.EventState = &eventState
}


// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r ModifyMaintenanceEventRequest) GetRegionId() string {
    return r.RegionId
}

type ModifyMaintenanceEventResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result ModifyMaintenanceEventResult `json:"result"`
}

type ModifyMaintenanceEventResult struct {
}