// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type PrefixListBindResource struct {

    /* 前缀列表ID (Optional) */
    PrefixListId string `json:"prefixListId"`

    /* 绑定资源类型 (Optional) */
    ResourceType string `json:"resourceType"`

    /* 绑定资源ID (Optional) */
    ResourceId string `json:"resourceId"`

    /* 绑定资源名称 (Optional) */
    ResourceName string `json:"resourceName"`

    /* 创建时间，时间格式为UTC (Optional) */
    CreatedTime string `json:"createdTime"`
}
