// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package models


type DeviceRespBody struct {

    /*  (Optional) */
    Tk string `json:"tk"`

    /*  (Optional) */
    IsStrategy string `json:"isStrategy"`

    /*  (Optional) */
    CltTime int `json:"cltTime"`

    /*  (Optional) */
    CltFreq int `json:"cltFreq"`

    /*  (Optional) */
    IsCltSensor string `json:"isCltSensor"`

    /*  (Optional) */
    TokenTime int `json:"tokenTime"`

    /*  (Optional) */
    TokenActTime int `json:"tokenActTime"`

    /*  (Optional) */
    Eid string `json:"eid"`

    /*  (Optional) */
    Ise string `json:"ise"`

    /*  (Optional) */
    Isr string `json:"isr"`

    /*  (Optional) */
    Ism string `json:"ism"`

    /*  (Optional) */
    Ish string `json:"ish"`

    /*  (Optional) */
    Isj string `json:"isj"`
}
