// Copyright 2018 JDCLOUD.COM
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// NOTE: This class is auto generated by the jdcloud code generator program.

package apis

import (
    "github.com/lshuining/jdcloud-sdk-go/core"
    vod "github.com/lshuining/jdcloud-sdk-go/services/vod/models"
)

type GetVeditProjectRequest struct {

    core.JDCloudRequest

    /* 视频剪辑工程ID  */
    ProjectId int `json:"projectId"`
}

/*
 * param projectId: 视频剪辑工程ID (Required)
 *
 * @Deprecated, not compatible when mandatory parameters changed
 */
func NewGetVeditProjectRequest(
    projectId int,
) *GetVeditProjectRequest {

	return &GetVeditProjectRequest{
        JDCloudRequest: core.JDCloudRequest{
			URL:     "/veditProjects/{projectId}",
			Method:  "GET",
			Header:  nil,
			Version: "v1",
		},
        ProjectId: projectId,
	}
}

/*
 * param projectId: 视频剪辑工程ID (Required)
 */
func NewGetVeditProjectRequestWithAllParams(
    projectId int,
) *GetVeditProjectRequest {

    return &GetVeditProjectRequest{
        JDCloudRequest: core.JDCloudRequest{
            URL:     "/veditProjects/{projectId}",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
        ProjectId: projectId,
    }
}

/* This constructor has better compatible ability when API parameters changed */
func NewGetVeditProjectRequestWithoutParam() *GetVeditProjectRequest {

    return &GetVeditProjectRequest{
            JDCloudRequest: core.JDCloudRequest{
            URL:     "/veditProjects/{projectId}",
            Method:  "GET",
            Header:  nil,
            Version: "v1",
        },
    }
}

/* param projectId: 视频剪辑工程ID(Required) */
func (r *GetVeditProjectRequest) SetProjectId(projectId int) {
    r.ProjectId = projectId
}

// GetRegionId returns path parameter 'regionId' if exist,
// otherwise return empty string
func (r GetVeditProjectRequest) GetRegionId() string {
    return ""
}

type GetVeditProjectResponse struct {
    RequestID string `json:"requestId"`
    Error core.ErrorResponse `json:"error"`
    Result GetVeditProjectResult `json:"result"`
}

type GetVeditProjectResult struct {
    ProjectId int64 `json:"projectId"`
    ProjectName string `json:"projectName"`
    Description string `json:"description"`
    Timeline vod.Timeline `json:"timeline"`
    CreateTime string `json:"createTime"`
    UpdateTime string `json:"updateTime"`
}